package com.jadhavr.erp.attendance.controller;
import com.jadhavr.erp.attendance.dto.AttendanceDtos.*;import com.jadhavr.erp.attendance.service.AttendanceService;import jakarta.validation.Valid;import org.springframework.format.annotation.DateTimeFormat;import org.springframework.http.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;import java.time.*;import java.util.*;
@RestController @RequestMapping("/api/attendance") public class AttendanceController {private final AttendanceService service;public AttendanceController(AttendanceService s){service=s;}
 @GetMapping("/sessions") public List<SessionResponse> sessions(@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate from,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate to){return service.list(from,to);}
 @PostMapping("/sessions/daily") @PreAuthorize("hasAnyRole('SUPER_ADMIN','ADMIN','PRINCIPAL','HOD','CLASS_TEACHER')") public SessionResponse daily(@Valid @RequestBody DailySessionRequest r){return service.createDaily(r);}
 @PostMapping("/sessions/{id}/submit") @PreAuthorize("hasAnyRole('SUPER_ADMIN','ADMIN','PRINCIPAL','HOD','CLASS_TEACHER','SUBJECT_TEACHER')") public SessionResponse submit(@PathVariable Long id,@Valid @RequestBody SubmitRequest r){return service.submit(id,r);}
 @PostMapping("/records/{id}/correct") @PreAuthorize("hasAnyRole('SUPER_ADMIN','ADMIN','PRINCIPAL','HOD','CLASS_TEACHER','SUBJECT_TEACHER')") public AttendanceItem correct(@PathVariable Long id,@Valid @RequestBody CorrectionRequest r){return service.correct(id,r);}
 @GetMapping("/reports/students/{studentId}") public ReportResponse report(@PathVariable Long studentId,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate from,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate to){return service.report(studentId,from,to);}
 @GetMapping(value="/reports/students/{studentId}/excel",produces="application/vnd.ms-excel") public ResponseEntity<byte[]> excel(@PathVariable Long studentId,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate from,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate to){return ResponseEntity.ok().header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=attendance.xls").body(service.exportExcel(studentId,from,to));}
 @GetMapping(value="/reports/students/{studentId}/pdf",produces=MediaType.APPLICATION_PDF_VALUE) public ResponseEntity<byte[]> pdf(@PathVariable Long studentId,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate from,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate to){return ResponseEntity.ok().header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=attendance.pdf").body(service.exportPdf(studentId,from,to));}
}
