package com.jadhavr.erp.fee.service;
import com.jadhavr.erp.admission.entity.AdmissionStatusHistory;
import com.jadhavr.erp.admission.enums.AdmissionAction;
import com.jadhavr.erp.admission.repository.AdmissionStatusHistoryRepository;
import com.jadhavr.erp.admission.entity.AdmissionForm; import com.jadhavr.erp.admission.enums.AdmissionStatus; import com.jadhavr.erp.admission.repository.AdmissionFormRepository; import com.jadhavr.erp.auth.security.SecurityUtils; import com.jadhavr.erp.college.entity.*; import com.jadhavr.erp.college.repository.CollegeRepository; import com.jadhavr.erp.common.dto.PageResponse; import com.jadhavr.erp.common.exception.*; import com.jadhavr.erp.department.entity.*; import com.jadhavr.erp.department.repository.DepartmentRepository; import com.jadhavr.erp.fee.dto.*; import com.jadhavr.erp.fee.entity.*; import com.jadhavr.erp.fee.enums.*; import com.jadhavr.erp.fee.repository.*; import com.jadhavr.erp.user.entity.User; import com.jadhavr.erp.user.repository.UserRepository; import org.springframework.data.domain.*; import org.springframework.data.jpa.domain.Specification; import org.springframework.security.access.AccessDeniedException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal; import java.time.*; import java.util.*;
import org.springframework.dao.DataIntegrityViolationException;
@Service @Transactional(readOnly=true) public class FeeServiceImpl implements FeeService {
 private final FeeStructureRepository structures; private final StudentFeeAccountRepository accounts; private final FeePaymentRepository payments; private final FeeTransactionRepository transactions; private final CollegeRepository colleges; private final DepartmentRepository departments; private final UserRepository users; private final AdmissionFormRepository admissions; private final AdmissionStatusHistoryRepository histories;
 public FeeServiceImpl(FeeStructureRepository s,StudentFeeAccountRepository a,FeePaymentRepository p,FeeTransactionRepository t,CollegeRepository c,DepartmentRepository d,UserRepository u,AdmissionFormRepository af,AdmissionStatusHistoryRepository h){structures=s;accounts=a;payments=p;transactions=t;colleges=c;departments=d;users=u;admissions=af;histories=h;}
 @Transactional public FeeStructureResponse createStructure(CreateFeeStructureRequest r){scope(r.collegeId()); validateAmounts(r.totalFee(),r.minimumAmountForAdmission()); College c=colleges.findById(r.collegeId()).orElseThrow(()->new ResourceNotFoundException("College not found")); Department d=departments.findById(r.departmentId()).orElseThrow(()->new ResourceNotFoundException("Department not found")); if(c.getStatus()!=CollegeStatus.ACTIVE||d.getStatus()!=DepartmentStatus.ACTIVE)throw new BadRequestException("Active college and department are required"); if(!d.getCollege().getId().equals(c.getId()))throw new BadRequestException("Department does not belong to college"); StudentCategory category=r.studentCategory()==null?StudentCategory.OPEN:r.studentCategory(); if(structures.existsByCollegeIdAndDepartmentIdAndAcademicYearAndStudentCategoryAndStatus(c.getId(),d.getId(),r.academicYear().trim(),category,FeeStructureStatus.ACTIVE))throw new DuplicateResourceException("Active fee structure already exists"); FeeStructure f=new FeeStructure(); f.setCollege(c);f.setDepartment(d);f.setAcademicYear(r.academicYear().trim());f.setStudentCategory(category); apply(f,r.title(),r.description(),r.totalFee(),r.minimumAmountForAdmission(),r.admissionFee(),r.tuitionFee(),r.examFee(),r.libraryFee(),r.otherFee()); return structure(structures.save(f));}
 @Transactional public FeeStructureResponse updateStructure(Long id,UpdateFeeStructureRequest r){FeeStructure f=findStructure(id);validateAmounts(r.totalFee(),r.minimumAmountForAdmission());apply(f,r.title(),r.description(),r.totalFee(),r.minimumAmountForAdmission(),r.admissionFee(),r.tuitionFee(),r.examFee(),r.libraryFee(),r.otherFee());if(r.status()!=null)f.setStatus(r.status());return structure(structures.save(f));}
 @Transactional public void deleteStructure(Long id){FeeStructure f=findStructure(id);if(accounts.existsByFeeStructureId(id))throw new BadRequestException("Fee structure cannot be deleted because student fee accounts use it. Deactivate it instead.");structures.delete(f);}
 @Transactional public FeeStructureResponse setStructureStatus(Long id,FeeStructureStatus s){FeeStructure f=findStructure(id); if(s==FeeStructureStatus.ACTIVE&&structures.existsByCollegeIdAndDepartmentIdAndAcademicYearAndStudentCategoryAndStatus(f.getCollege().getId(),f.getDepartment().getId(),f.getAcademicYear(),f.getStudentCategory(),s)&&f.getStatus()!=s)throw new DuplicateResourceException("Active fee structure already exists");f.setStatus(s);return structure(structures.save(f));}
 public FeeStructureResponse getStructure(Long id){return structure(findStructure(id));}
 public PageResponse<FeeStructureResponse> searchStructures(String k,Long c,Long d,String y,FeeStructureStatus s,int p,int z,String sort,String dir){return searchStructures(k,c,d,y,null,s,p,z,sort,dir);}
 public PageResponse<FeeStructureResponse> searchStructures(String k,Long c,Long d,String y,StudentCategory category,FeeStructureStatus s,int p,int z,String sort,String dir){validPage(p,z);Long sc=scoped(c);Specification<FeeStructure>x=Specification.where(null);if(sc!=null)x=x.and((r,q,b)->b.equal(r.get("college").get("id"),sc));if(d!=null)x=x.and((r,q,b)->b.equal(r.get("department").get("id"),d));if(y!=null&&!y.isBlank())x=x.and((r,q,b)->b.equal(r.get("academicYear"),y));if(category!=null)x=x.and((r,q,b)->b.equal(r.get("studentCategory"),category));if(s!=null)x=x.and((r,q,b)->b.equal(r.get("status"),s));if(k!=null&&!k.isBlank()){String v="%"+k.toLowerCase()+"%";x=x.and((r,q,b)->b.or(b.like(b.lower(r.get("title")),v),b.like(b.lower(r.get("department").get("name")),v)));}return PageResponse.from(structures.findAll(x,PageRequest.of(p,z,Sort.by(direction(dir),Set.of("createdAt","title","totalFee","academicYear").contains(sort)?sort:"createdAt"))).map(this::structure));}
 @Transactional public void createAccountForAdmission(AdmissionForm a){if(accounts.existsByAdmissionFormId(a.getId()))return;StudentCategory category=a.getStudentCategory();if(category==null)throw new BadRequestException("Student category must be verified before fee account creation");FeeStructure f=structures.findByCollegeIdAndDepartmentIdAndAcademicYearAndStudentCategoryAndStatus(a.getCollege().getId(),a.getDepartment().getId(),a.getAcademicYear(),category,FeeStructureStatus.ACTIVE).orElseThrow(()->new BadRequestException("Active "+category+" fee structure not found for this department and academic year"));StudentFeeAccount x=new StudentFeeAccount();x.setStudent(a.getStudent());x.setStudentUser(a.getStudentUser());x.setAdmissionForm(a);x.setCollege(a.getCollege());x.setDepartment(a.getDepartment());x.setFeeStructure(f);x.setAcademicYear(a.getAcademicYear());x.setStudentCategory(category);x.setTotalFee(f.getTotalFee());x.setRemainingAmount(f.getTotalFee());x.setMinimumAmountForAdmission(f.getMinimumAmountForAdmission());accounts.save(x);saveHistory(a,a.getStatus(),AdmissionAction.FEE_ACCOUNT_CREATED,null,"Fee account created for verified category "+category);}
 public StudentFeeAccountResponse myAccount(){return account(currentAccount());}
 @Transactional public PaymentResponse submitPayment(SubmitPaymentRequest r){StudentFeeAccount a=currentAccount();if(a.getRemainingAmount().signum()<=0)throw new BadRequestException("Fee account is already paid");if(r.amount().compareTo(a.getRemainingAmount())>0)throw new BadRequestException("Payment amount exceeds remaining fee");if(payments.existsByCollegeIdAndTransactionReferenceIgnoreCase(a.getCollege().getId(),r.transactionReference().trim()))throw new DuplicateResourceException("Transaction reference already exists");FeePayment p=new FeePayment();p.setStudentFeeAccount(a);p.setStudent(a.getStudent());p.setStudentUser(a.getStudentUser());p.setCollege(a.getCollege());p.setDepartment(a.getDepartment());p.setAmount(r.amount());p.setPaymentMode(r.paymentMode());p.setTransactionReference(r.transactionReference().trim());p.setPaymentDate(r.paymentDate());p.setProofUrl(r.proofUrl().trim());p.setRemarks(trim(r.remarks()));p.setSubmittedAt(LocalDateTime.now());try{return payment(payments.saveAndFlush(p));}catch(DataIntegrityViolationException e){throw new DuplicateResourceException("Transaction reference already exists");}}
 public List<PaymentResponse> myPayments(){return payments.findByStudentUserIdOrderByCreatedAtDesc(SecurityUtils.getCurrentUserId()).stream().map(this::payment).toList();} public List<FeeTransactionResponse> myTransactions(){return accountTransactions(currentAccount().getId());}
 public FeeDashboardResponse dashboard(){LocalDateTime start=LocalDate.now().atStartOfDay();if(SecurityUtils.isSuperAdmin())return new FeeDashboardResponse(accounts.count(),payments.countByStatus(PaymentStatus.PENDING),payments.countByStatus(PaymentStatus.VERIFIED),payments.countByStatus(PaymentStatus.REJECTED),payments.sumByStatus(PaymentStatus.VERIFIED),payments.sumByStatus(PaymentStatus.PENDING),payments.sumTodayAll(start));Long c=requireCollege();return new FeeDashboardResponse(accounts.countByCollegeId(c),payments.countByCollegeIdAndStatus(c,PaymentStatus.PENDING),payments.countByCollegeIdAndStatus(c,PaymentStatus.VERIFIED),payments.countByCollegeIdAndStatus(c,PaymentStatus.REJECTED),payments.sumByCollegeAndStatus(c,PaymentStatus.VERIFIED),payments.sumByCollegeAndStatus(c,PaymentStatus.PENDING),payments.sumToday(c,start));}
 public PageResponse<StudentFeeAccountResponse> searchAccounts(String k,Long c,Long d,FeeAccountStatus s,int p,int z){Long sc=scoped(c);Specification<StudentFeeAccount>x=Specification.where(null);if(sc!=null)x=x.and((r,q,b)->b.equal(r.get("college").get("id"),sc));if(d!=null)x=x.and((r,q,b)->b.equal(r.get("department").get("id"),d));if(s!=null)x=x.and((r,q,b)->b.equal(r.get("status"),s));if(k!=null&&!k.isBlank()){String v="%"+k.toLowerCase()+"%";x=x.and((r,q,b)->b.or(b.like(b.lower(r.get("student").get("fullName")),v),b.like(b.lower(r.get("student").get("admissionNumber")),v)));}return PageResponse.from(accounts.findAll(x,PageRequest.of(p,z,Sort.by(Sort.Direction.DESC,"createdAt"))).map(this::account));}
 public StudentFeeAccountResponse getAccount(Long id){StudentFeeAccount a=accounts.findById(id).orElseThrow(()->new ResourceNotFoundException("Fee account not found"));scope(a.getCollege().getId());return account(a);}
 public PageResponse<PaymentResponse> searchPayments(String k,Long c,Long d,PaymentStatus s,int p,int z){Long sc=scoped(c);Specification<FeePayment>x=Specification.where(null);if(sc!=null)x=x.and((r,q,b)->b.equal(r.get("college").get("id"),sc));if(d!=null)x=x.and((r,q,b)->b.equal(r.get("department").get("id"),d));if(s!=null)x=x.and((r,q,b)->b.equal(r.get("status"),s));if(k!=null&&!k.isBlank()){String v="%"+k.toLowerCase()+"%";x=x.and((r,q,b)->b.or(b.like(b.lower(r.get("transactionReference")),v),b.like(b.lower(r.get("student").get("fullName")),v)));}return PageResponse.from(payments.findAll(x,PageRequest.of(p,z,Sort.by(Sort.Direction.DESC,"createdAt"))).map(this::payment));}
 public PaymentResponse getPayment(Long id){return payment(scopedPayment(id));}
 @Transactional public PaymentResponse verify(Long id,VerifyPaymentRequest r){FeePayment p=scopedPaymentForUpdate(id);if(p.getStatus()!=PaymentStatus.PENDING)throw new BadRequestException(p.getStatus()==PaymentStatus.VERIFIED?"Payment already verified":"Payment already rejected");StudentFeeAccount a=accounts.findByIdForUpdate(p.getStudentFeeAccount().getId()).orElseThrow(()->new ResourceNotFoundException("Fee account not found"));if(transactions.existsByFeePaymentId(p.getId()))throw new BadRequestException("Payment has already been processed");BigDecimal oldPaid=a.getPaidAmount(),oldRemaining=a.getRemainingAmount();if(p.getAmount().compareTo(oldRemaining)>0)throw new BadRequestException("Payment amount exceeds remaining fee");BigDecimal newPaid=oldPaid.add(p.getAmount()),newRemaining=oldRemaining.subtract(p.getAmount());if(newPaid.compareTo(a.getTotalFee())>0||newRemaining.signum()<0)throw new BadRequestException("Payment would create an invalid fee balance");a.setPaidAmount(newPaid);a.setRemainingAmount(newRemaining);a.setStatus(newRemaining.signum()==0?FeeAccountStatus.PAID:FeeAccountStatus.PARTIALLY_PAID);User u=currentUser();p.setStatus(PaymentStatus.VERIFIED);p.setVerifiedAt(LocalDateTime.now());p.setVerifiedBy(u);p.setRemarks(trim(r.remarks()));FeeTransaction t=transaction(p,FeeTransactionType.PAYMENT_VERIFIED,u,r.remarks());t.setStudentFeeAccount(a);t.setPreviousPaidAmount(oldPaid);t.setNewPaidAmount(newPaid);t.setPreviousRemainingAmount(oldRemaining);t.setNewRemainingAmount(newRemaining);transactions.save(t);accounts.save(a);if(newPaid.compareTo(a.getMinimumAmountForAdmission())>=0){a.getAdmissionForm().setStatus(AdmissionStatus.PRINCIPAL_REVIEW_PENDING);admissions.save(a.getAdmissionForm());saveHistory(a.getAdmissionForm(),AdmissionStatus.PRINCIPAL_REVIEW_PENDING,AdmissionAction.PRINCIPAL_REVIEW_PENDING,u,"Minimum required fee verified");}else saveHistory(a.getAdmissionForm(),a.getAdmissionForm().getStatus(),AdmissionAction.PAYMENT_VERIFIED,u,"Payment verified");return payment(payments.save(p));}
 @Transactional public PaymentResponse reject(Long id,RejectPaymentRequest r){FeePayment p=scopedPaymentForUpdate(id);if(p.getStatus()!=PaymentStatus.PENDING)throw new BadRequestException(p.getStatus()==PaymentStatus.VERIFIED?"Payment already verified":"Payment already rejected");if(transactions.existsByFeePaymentId(p.getId()))throw new BadRequestException("Payment has already been processed");User u=currentUser();p.setStatus(PaymentStatus.REJECTED);p.setRejectedAt(LocalDateTime.now());p.setRejectedBy(u);p.setRejectionReason(r.rejectionReason().trim());transactions.save(transaction(p,FeeTransactionType.PAYMENT_REJECTED,u,r.rejectionReason()));saveHistory(p.getStudentFeeAccount().getAdmissionForm(),p.getStudentFeeAccount().getAdmissionForm().getStatus(),AdmissionAction.PAYMENT_REJECTED,u,r.rejectionReason());return payment(payments.save(p));}
 public List<FeeTransactionResponse> accountTransactions(Long id){StudentFeeAccount a=accounts.findById(id).orElseThrow(()->new ResourceNotFoundException("Fee account not found"));if(SecurityUtils.isSuperAdmin()||SecurityUtils.getCurrentUserId().equals(a.getStudentUser().getId())){}else scope(a.getCollege().getId());return transactions.findByStudentFeeAccountIdOrderByCreatedAtDesc(id).stream().map(this::transactionResponse).toList();}
 private FeeTransaction transaction(FeePayment p,FeeTransactionType type,User u,String remarks){FeeTransaction t=new FeeTransaction();t.setStudentFeeAccount(p.getStudentFeeAccount());t.setFeePayment(p);t.setTransactionType(type);t.setAmount(p.getAmount());t.setPerformedBy(u);t.setRemarks(trim(remarks));return t;} private StudentFeeAccount currentAccount(){return accounts.findTopByStudentUserIdOrderByCreatedAtDesc(SecurityUtils.getCurrentUserId()).orElseThrow(()->new ResourceNotFoundException("Fee account is not generated yet. Please wait for Student Section verification."));} private FeePayment scopedPayment(Long id){FeePayment p=payments.findById(id).orElseThrow(()->new ResourceNotFoundException("Payment not found"));scope(p.getCollege().getId());return p;} private FeePayment scopedPaymentForUpdate(Long id){FeePayment p=payments.findByIdForUpdate(id).orElseThrow(()->new ResourceNotFoundException("Payment not found"));scope(p.getCollege().getId());return p;} private FeeStructure findStructure(Long id){FeeStructure f=structures.findById(id).orElseThrow(()->new ResourceNotFoundException("Fee structure not found"));scope(f.getCollege().getId());return f;} private User currentUser(){return users.findById(SecurityUtils.getCurrentUserId()).orElseThrow(()->new ResourceNotFoundException("Current user not found"));}
 private void scope(Long c){if(!SecurityUtils.isSuperAdmin()&&!Objects.equals(requireCollege(),c))throw new AccessDeniedException("Access denied");} private Long scoped(Long c){if(SecurityUtils.isSuperAdmin())return c;Long own=requireCollege();if(c!=null&&!c.equals(own))throw new AccessDeniedException("Access denied");return own;} private Long requireCollege(){Long c=SecurityUtils.requireCurrentUser().getCollegeId();if(c==null)throw new AccessDeniedException("College access required");return c;} private void validPage(int p,int z){if(p<0||z<1||z>100)throw new BadRequestException("Invalid pagination");} private Sort.Direction direction(String d){return "asc".equalsIgnoreCase(d)?Sort.Direction.ASC:Sort.Direction.DESC;} private void validateAmounts(BigDecimal t,BigDecimal m){if(m.compareTo(t)>0)throw new BadRequestException("Minimum amount cannot exceed total fee");}
 private void apply(FeeStructure f,String title,String desc,BigDecimal total,BigDecimal min,BigDecimal admission,BigDecimal tuition,BigDecimal exam,BigDecimal library,BigDecimal other){f.setTitle(title.trim());f.setDescription(trim(desc));f.setTotalFee(total);f.setMinimumAmountForAdmission(min);f.setAdmissionFee(admission);f.setTuitionFee(tuition);f.setExamFee(exam);f.setLibraryFee(library);f.setOtherFee(other);} private String trim(String v){return v==null||v.isBlank()?null:v.trim();}
 private FeeStructureResponse structure(FeeStructure f){return new FeeStructureResponse(f.getId(),f.getCollege().getId(),f.getCollege().getName(),f.getCollege().getCode(),f.getDepartment().getId(),f.getDepartment().getName(),f.getDepartment().getCode(),f.getAcademicYear(),f.getTitle(),f.getDescription(),f.getTotalFee(),f.getMinimumAmountForAdmission(),f.getAdmissionFee(),f.getTuitionFee(),f.getExamFee(),f.getLibraryFee(),f.getOtherFee(),f.getStudentCategory(),f.getStatus(),f.getCreatedAt(),f.getUpdatedAt());}
 private StudentFeeAccountResponse account(StudentFeeAccount a){return new StudentFeeAccountResponse(a.getId(),a.getStudent().getId(),a.getStudentUser().getId(),a.getAdmissionForm().getId(),a.getAdmissionForm().getAdmissionReferenceNumber(),a.getStudent().getAdmissionNumber(),a.getCollege().getId(),a.getCollege().getName(),a.getCollege().getCode(),a.getDepartment().getId(),a.getDepartment().getName(),a.getDepartment().getCode(),a.getAcademicYear(),a.getStudentCategory(),a.getTotalFee(),a.getPaidAmount(),a.getRemainingAmount(),a.getDiscountAmount(),a.getMinimumAmountForAdmission(),a.getStatus(),a.getCollege().getQrCodeUrl(),"Scan the college QR code and pay manually. Then submit payment proof.",a.getCreatedAt(),a.getUpdatedAt());}
 private PaymentResponse payment(FeePayment p){return new PaymentResponse(p.getId(),p.getStudentFeeAccount().getId(),p.getStudent().getId(),p.getStudent().getFullName(),p.getStudent().getAdmissionNumber(),p.getCollege().getId(),p.getCollege().getName(),p.getDepartment().getId(),p.getDepartment().getName(),p.getAmount(),p.getPaymentMode(),p.getTransactionReference(),p.getPaymentDate(),p.getProofUrl(),p.getRemarks(),p.getStatus(),p.getSubmittedAt(),p.getVerifiedAt(),p.getVerifiedBy()==null?null:p.getVerifiedBy().getFullName(),p.getRejectedAt(),p.getRejectedBy()==null?null:p.getRejectedBy().getFullName(),p.getRejectionReason(),p.getCreatedAt(),p.getUpdatedAt());}
 private void saveHistory(AdmissionForm a,AdmissionStatus status,AdmissionAction action,User by,String remarks){AdmissionStatusHistory h=new AdmissionStatusHistory();h.setAdmissionForm(a);h.setChangedBy(by);h.setOldStatus(a.getStatus());h.setNewStatus(status);h.setAction(action);h.setRemarks(remarks);histories.save(h);} private FeeTransactionResponse transactionResponse(FeeTransaction t){return new FeeTransactionResponse(t.getId(),t.getStudentFeeAccount().getId(),t.getFeePayment()==null?null:t.getFeePayment().getId(),t.getTransactionType(),t.getAmount(),t.getPreviousPaidAmount(),t.getNewPaidAmount(),t.getPreviousRemainingAmount(),t.getNewRemainingAmount(),t.getRemarks(),t.getPerformedBy()==null?null:t.getPerformedBy().getFullName(),t.getCreatedAt());}
}




