package com.jadhavr.erp.admission.dto;

import com.jadhavr.erp.admission.enums.AdmissionSource;
import com.jadhavr.erp.admission.enums.AdmissionStatus;
import com.jadhavr.erp.admission.enums.AdmissionDocumentType;
import com.jadhavr.erp.academic.enums.CourseYearName;
import com.jadhavr.erp.fee.enums.StudentCategory;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

public record StudentSectionAdmissionResponse(
        Long id,
        String admissionReferenceNumber,
        String admissionNumber,
        Long collegeId,
        String collegeName,
        String collegeCode,
        Long departmentId,
        String departmentName,
        String departmentCode,
        String academicYear,
        Long courseYearId,
        CourseYearName courseYearName,
        String courseYearDisplayName,
        StudentCategory studentCategory,
        String fullName,
        String email,
        String phone,
        LocalDate dateOfBirth,
        String gender,
        String addressLine1,
        String addressLine2,
        String city,
        String state,
        String pincode,
        String parentName,
        String parentPhone,
        String parentEmail,
        String previousSchoolName,
        String previousClassName,
        BigDecimal previousPercentage,
        boolean photoAvailable,
        String placeOfBirth,
        String maritalStatus,
        String aadhaarNumber,
        String apaarId,
        String nationality,
        String religion,
        String caste,
        String permanentPhone,
        String permanentEmail,
        String correspondenceAddress,
        String correspondenceCity,
        String correspondencePincode,
        String correspondenceState,
        String correspondencePhone,
        String correspondenceMobile,
        String correspondenceEmail,
        java.util.List<AcademicRecordDto> academicRecords,
        String qualifyingEntranceSeatNumber,
        BigDecimal qualifyingEntranceTotalScore,
        String lastGraduationCollegeName,
        String lastGraduationCollegeAddress,
        java.util.Set<AdmissionDocumentType> uploadedDocuments,
        LocalDateTime detailsCompletedAt,
        LocalDateTime principalApprovedAt,
        AdmissionStatus status,
        AdmissionSource source,
        LocalDateTime submittedAt,
        LocalDateTime studentSectionVerifiedAt,
        String studentSectionVerifiedByName,
        String studentSectionRemarks,
        LocalDateTime studentSectionRejectedAt,
        String studentSectionRejectedByName,
        String rejectionReason,
        LocalDateTime lastPrintedAt,
        String lastPrintedByName,
        Integer printCount,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
) {
}
