package com.jadhavr.erp.academic.service;
import com.jadhavr.erp.academic.dto.AcademicDtos.*; import com.jadhavr.erp.academic.entity.*; import com.jadhavr.erp.academic.enums.*; import com.jadhavr.erp.academic.repository.*; import com.jadhavr.erp.auth.security.*; import com.jadhavr.erp.college.entity.*; import com.jadhavr.erp.college.repository.*; import com.jadhavr.erp.common.exception.*; import com.jadhavr.erp.department.entity.*; import com.jadhavr.erp.department.repository.*; import com.jadhavr.erp.staff.entity.*; import com.jadhavr.erp.staff.enums.*; import com.jadhavr.erp.staff.repository.*; import com.jadhavr.erp.student.entity.*; import com.jadhavr.erp.student.enums.*; import com.jadhavr.erp.student.repository.*; import org.springframework.security.access.AccessDeniedException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @Transactional public class AcademicServiceImpl implements AcademicService {
 private final AcademicClassRepository classes; private final SectionRepository sections; private final SubjectRepository subjects; private final StudentSectionEnrollmentRepository enrollments; private final SubjectTeacherAssignmentRepository assignments; private final TimetableEntryRepository timetable; private final AttendanceSessionRepository sessions; private final AttendanceRecordRepository records; private final CollegeRepository colleges; private final DepartmentRepository departments; private final StaffProfileRepository staff; private final StudentProfileRepository students;
 public AcademicServiceImpl(AcademicClassRepository a,SectionRepository s,SubjectRepository su,StudentSectionEnrollmentRepository e,SubjectTeacherAssignmentRepository as,TimetableEntryRepository t,AttendanceSessionRepository se,AttendanceRecordRepository r,CollegeRepository c,DepartmentRepository d,StaffProfileRepository st,StudentProfileRepository sp){classes=a;sections=s;subjects=su;enrollments=e;assignments=as;timetable=t;sessions=se;records=r;colleges=c;departments=d;staff=st;students=sp;}
 public AcademicClass createClass(CreateClass r){ scope(r.collegeId(),r.departmentId()); College c=colleges.findById(r.collegeId()).orElseThrow(()->new ResourceNotFoundException("College not found")); Department d=departments.findById(r.departmentId()).orElseThrow(()->new ResourceNotFoundException("Department not found")); if(c.getStatus()!=CollegeStatus.ACTIVE||d.getStatus()!=DepartmentStatus.ACTIVE)throw new BadRequestException("College and department must be active"); String code=up(r.code()); if(classes.existsByCollegeIdAndDepartmentIdAndAcademicYearAndCodeIgnoreCase(c.getId(),d.getId(),r.academicYear(),code))throw new DuplicateResourceException("Class code already exists"); AcademicClass x=new AcademicClass();x.setCollege(c);x.setDepartment(d);x.setAcademicYear(r.academicYear());x.setName(r.name().trim());x.setCode(code);x.setDescription(r.description());return classes.save(x);}
 @Transactional(readOnly=true) public List<Map<String,Object>> classes(Long d){return classes.findAll().stream().filter(x->visible(x.getCollege().getId(),x.getDepartment().getId())&&(d==null||d.equals(x.getDepartment().getId()))).map(this::classView).toList();}
 public AcademicClass classStatus(Long id,boolean active){AcademicClass x=classes.findById(id).orElseThrow(()->new ResourceNotFoundException("Class not found"));scope(x.getCollege().getId(),x.getDepartment().getId());x.setStatus(active?AcademicStatus.ACTIVE:AcademicStatus.INACTIVE);return x;}
 public Section createSection(CreateSection r){AcademicClass c=classes.findById(r.academicClassId()).orElseThrow(()->new ResourceNotFoundException("Class not found"));scope(c.getCollege().getId(),c.getDepartment().getId());if(c.getStatus()!=AcademicStatus.ACTIVE)throw new BadRequestException("Class is inactive");String code=up(r.code());if(sections.existsByAcademicClassIdAndAcademicYearAndCodeIgnoreCase(c.getId(),r.academicYear(),code))throw new DuplicateResourceException("Section code already exists");Section x=new Section();x.setCollege(c.getCollege());x.setDepartment(c.getDepartment());x.setAcademicClass(c);x.setAcademicYear(r.academicYear());x.setName(r.name().trim());x.setCode(code);x.setCapacity(r.capacity());return sections.save(x);}
 @Transactional(readOnly=true) public List<Map<String,Object>> sections(Long c){return sections.findAll().stream().filter(x->visible(x.getCollege().getId(),x.getDepartment().getId())&&(c==null||c.equals(x.getAcademicClass().getId()))).map(this::sectionView).toList();}
 public Section assignClassTeacher(Long id,Assign r){Section x=section(id);StaffProfile t=staff.findById(r.staffProfileId()).orElseThrow(()->new ResourceNotFoundException("Staff not found"));same(x,t,StaffType.CLASS_TEACHER);x.setClassTeacher(t);return x;}
 public Map<String,Object> assignStudent(Long id,AssignStudent r){Section x=section(id);StudentProfile s=students.findById(r.studentProfileId()).orElseThrow(()->new ResourceNotFoundException("Student not found"));if(s.getStatus()!=StudentStatus.ACTIVE||!s.getCollege().getId().equals(x.getCollege().getId())||!s.getDepartment().getId().equals(x.getDepartment().getId()))throw new BadRequestException("Student must be active and belong to the section department");if(enrollments.existsByStudentIdAndAcademicYearAndStatus(s.getId(),x.getAcademicYear(),AcademicStatus.ACTIVE))throw new DuplicateResourceException("Student already enrolled for this academic year");if(enrollments.countBySectionIdAndStatus(id,AcademicStatus.ACTIVE)>=x.getCapacity())throw new BadRequestException("Section capacity reached");StudentSectionEnrollment e=new StudentSectionEnrollment();e.setStudent(s);e.setSection(x);e.setAcademicClass(x.getAcademicClass());e.setAcademicYear(x.getAcademicYear());e.setRollNumber(s.getRollNumber());StudentSectionEnrollment saved=enrollments.save(e);return Map.of("enrollmentId",saved.getId(),"studentProfileId",s.getId(),"sectionId",x.getId(),"division",x.getName(),"academicYear",x.getAcademicYear());}
 public Map<String,Object> createSubject(CreateSubject r){AcademicClass c=classes.findById(r.academicClassId()).orElseThrow(()->new ResourceNotFoundException("Class not found"));scope(c.getCollege().getId(),c.getDepartment().getId());String code=up(r.code());if(subjects.existsByAcademicClassIdAndAcademicYearAndCodeIgnoreCase(c.getId(),r.academicYear(),code))throw new DuplicateResourceException("Subject code already exists");Subject x=new Subject();x.setCollege(c.getCollege());x.setDepartment(c.getDepartment());x.setAcademicClass(c);x.setAcademicYear(r.academicYear());x.setName(r.name().trim());x.setCode(code);x.setDescription(r.description());x.setCredits(r.credits());Subject saved=subjects.save(x);return subjectView(saved);}
 @Transactional(readOnly=true) public List<Map<String,Object>> subjects(Long c){return subjects.findAll().stream().filter(x->visible(x.getCollege().getId(),x.getDepartment().getId())&&(c==null||c.equals(x.getAcademicClass().getId()))).map(this::subjectView).toList();}
 public SubjectTeacherAssignment assignTeacher(Long id,Assign r){Subject s=subjects.findById(id).orElseThrow(()->new ResourceNotFoundException("Subject not found"));scope(s.getCollege().getId(),s.getDepartment().getId());StaffProfile t=staff.findById(r.staffProfileId()).orElseThrow(()->new ResourceNotFoundException("Staff not found"));same(s.getCollege().getId(),s.getDepartment().getId(),t,StaffType.SUBJECT_TEACHER);if(assignments.existsBySubjectIdAndStatus(id,AcademicStatus.ACTIVE))throw new DuplicateResourceException("Subject already has an active teacher");SubjectTeacherAssignment a=new SubjectTeacherAssignment();a.setSubject(s);a.setTeacher(t);a.setAcademicYear(s.getAcademicYear());return assignments.save(a);}
 public TimetableEntry createTimetable(CreateTimetable r){Section s=section(r.sectionId());Subject u=subjects.findById(r.subjectId()).orElseThrow(()->new ResourceNotFoundException("Subject not found"));StaffProfile t=staff.findById(r.teacherId()).orElseThrow(()->new ResourceNotFoundException("Teacher not found"));same(s,t,StaffType.SUBJECT_TEACHER);if(!u.getAcademicClass().getId().equals(s.getAcademicClass().getId())||!r.endTime().isAfter(r.startTime()))throw new BadRequestException("Invalid subject or time range");if(!assignments.existsBySubjectIdAndTeacherIdAndStatus(u.getId(),t.getId(),AcademicStatus.ACTIVE))throw new BadRequestException("Teacher is not assigned to subject");if(timetable.hasClash(s.getId(),t.getId(),r.dayOfWeek(),r.startTime(),r.endTime()))throw new BadRequestException("Section or teacher timetable clash");TimetableEntry e=new TimetableEntry();e.setSection(s);e.setSubject(u);e.setTeacher(t);e.setDayOfWeek(r.dayOfWeek());e.setStartTime(r.startTime());e.setEndTime(r.endTime());e.setRoomNumber(r.roomNumber());return timetable.save(e);}
 @Transactional(readOnly=true) public List<TimetableEntry> timetable(Long id){Section s=section(id);return timetable.findBySectionIdAndStatusOrderByDayOfWeekAscStartTimeAsc(s.getId(),AcademicStatus.ACTIVE);}
 public AttendanceSession createAttendance(CreateAttendance r){Section s=section(r.sectionId());Subject u=subjects.findById(r.subjectId()).orElseThrow(()->new ResourceNotFoundException("Subject not found"));StaffProfile teacher=currentStaff();if(!assignments.existsBySubjectIdAndTeacherIdAndStatus(u.getId(),teacher.getId(),AcademicStatus.ACTIVE))throw new AccessDeniedException("Teacher is not assigned to subject");AttendanceSession a=new AttendanceSession();a.setSection(s);a.setSubject(u);a.setTeacher(teacher);a.setAttendanceDate(r.attendanceDate());a.setTopic(r.topic());if(r.timetableEntryId()!=null)a.setTimetableEntry(timetable.findById(r.timetableEntryId()).orElseThrow(()->new ResourceNotFoundException("Timetable entry not found")));a=sessions.save(a);for(StudentSectionEnrollment e:enrollments.findBySectionIdAndStatus(s.getId(),AcademicStatus.ACTIVE)){AttendanceRecord ar=new AttendanceRecord();ar.setSession(a);ar.setStudent(e.getStudent());records.save(ar);}return a;}
 public AttendanceSession mark(Long id,Mark r){AttendanceSession s=session(id);if(s.getStatus()!=AttendanceSessionStatus.OPEN)throw new BadRequestException("Submitted attendance cannot be edited");for(MarkItem i:r.records()){AttendanceRecord a=records.findBySessionIdAndStudentId(id,i.studentProfileId()).orElseThrow(()->new BadRequestException("Student is not enrolled in this session"));a.setStatus(i.status());a.setRemarks(i.remarks());}return s;}
 public AttendanceSession submit(Long id){AttendanceSession s=session(id);if(s.getStatus()!=AttendanceSessionStatus.OPEN)throw new BadRequestException("Attendance already submitted");s.setStatus(AttendanceSessionStatus.SUBMITTED);return s;}
 @Transactional(readOnly=true) public Map<String,Object> attendanceSummary(Long id){List<AttendanceRecord> a=records.findByStudentId(id).stream().filter(x->x.getSession().getStatus()==AttendanceSessionStatus.SUBMITTED).toList();long p=a.stream().filter(x->x.getStatus()==AttendanceStatus.PRESENT||x.getStatus()==AttendanceStatus.LATE).count();return Map.of("studentProfileId",id,"totalSessions",a.size(),"presentSessions",p,"percentage",a.isEmpty()?0.0:p*100.0/a.size());}
 @Transactional(readOnly=true) public List<StudentRosterItem> eligibleStudents(Long academicClassId){AcademicClass c=classes.findById(academicClassId).orElseThrow(()->new ResourceNotFoundException("Class not found"));scope(c.getCollege().getId(),c.getDepartment().getId());return students.findByDepartmentId(c.getDepartment().getId()).stream().filter(s->s.getStatus()==StudentStatus.ACTIVE).filter(s->!enrollments.existsByStudentIdAndAcademicYearAndStatus(s.getId(),c.getAcademicYear(),AcademicStatus.ACTIVE)).map(this::roster).toList();}
 @Transactional(readOnly=true) public List<StudentRosterItem> sectionStudents(Long sectionId){Section s=section(sectionId);return enrollments.findBySectionIdAndStatus(s.getId(),AcademicStatus.ACTIVE).stream().map(e->roster(e.getStudent())).toList();}
 @Transactional(readOnly=true) public Map<String,Object> classTeacherRoster(){StaffProfile teacher=currentStaff();Section section=sections.findByClassTeacherIdAndStatus(teacher.getId(),SectionStatus.ACTIVE).stream().findFirst().orElseThrow(()->new ResourceNotFoundException("No active class is assigned to you"));return classDetails(section);}
 @Transactional(readOnly=true) public Map<String,Object> studentClass(){StudentProfile student=students.findByUserId(SecurityUtils.requireCurrentUser().getId()).orElseThrow(()->new ResourceNotFoundException("Student profile not found"));StudentSectionEnrollment enrollment=enrollments.findFirstByStudentAndStatus(student,AcademicStatus.ACTIVE).orElseThrow(()->new ResourceNotFoundException("You have not been assigned to a class yet"));return classDetails(enrollment.getSection());}
 private Map<String,Object> classView(AcademicClass c){Map<String,Object> view=new LinkedHashMap<>();view.put("id",c.getId());view.put("college",Map.of("id",c.getCollege().getId(),"name",c.getCollege().getName()));view.put("department",Map.of("id",c.getDepartment().getId(),"name",c.getDepartment().getName()));view.put("academicYear",c.getAcademicYear());view.put("name",c.getName());view.put("code",c.getCode());view.put("description",c.getDescription());view.put("status",c.getStatus());return view;}
 private Map<String,Object> sectionView(Section s){Map<String,Object> view=new LinkedHashMap<>();view.put("id",s.getId());view.put("academicClass",classView(s.getAcademicClass()));view.put("academicYear",s.getAcademicYear());view.put("name",s.getName());view.put("code",s.getCode());view.put("capacity",s.getCapacity());view.put("status",s.getStatus());if(s.getClassTeacher()!=null)view.put("classTeacher",Map.of("id",s.getClassTeacher().getId(),"fullName",s.getClassTeacher().getFullName()));return view;}
 private Map<String,Object> subjectView(Subject s){Map<String,Object> view=new LinkedHashMap<>();view.put("id",s.getId());view.put("academicClass",classView(s.getAcademicClass()));view.put("academicYear",s.getAcademicYear());view.put("name",s.getName());view.put("code",s.getCode());view.put("description",s.getDescription());view.put("credits",s.getCredits());view.put("status",s.getStatus());return view;}
 private StudentRosterItem roster(StudentProfile s){return new StudentRosterItem(s.getId(),s.getAdmissionNumber(),s.getRollNumber(),s.getFullName(),s.getEmail(),s.getPhone());}
 private Map<String,Object> classDetails(Section s){return Map.of("sectionId",s.getId(),"className",s.getAcademicClass().getName(),"courseYear",s.getAcademicClass().getYearName().name(),"division",s.getName(),"divisionCode",s.getCode(),"department",s.getDepartment().getName(),"academicYear",s.getAcademicYear(),"classTeacher",s.getClassTeacher()==null?"Not assigned":s.getClassTeacher().getFullName(),"students",sectionStudents(s.getId()));} private Section section(Long id){Section x=sections.findById(id).orElseThrow(()->new ResourceNotFoundException("Section not found"));scope(x.getCollege().getId(),x.getDepartment().getId());return x;} private AttendanceSession session(Long id){AttendanceSession s=sessions.findById(id).orElseThrow(()->new ResourceNotFoundException("Attendance session not found"));scope(s.getSection().getCollege().getId(),s.getSection().getDepartment().getId());return s;} private StaffProfile currentStaff(){return staff.findByUserId(SecurityUtils.requireCurrentUser().getId()).orElseThrow(()->new AccessDeniedException("Staff profile required"));}
 private void same(Section s,StaffProfile t,StaffType type){same(s.getCollege().getId(),s.getDepartment().getId(),t,type);} private void same(Long c,Long d,StaffProfile t,StaffType type){if(t.getStaffType()!=type||!t.getCollege().getId().equals(c)||t.getDepartment()==null||!t.getDepartment().getId().equals(d))throw new BadRequestException("Teacher type, college or department does not match");}
 private void scope(Long c,Long d){if(!visible(c,d))throw new AccessDeniedException("Academic resource is outside your scope");} private boolean visible(Long c,Long d){CustomUserDetails u=SecurityUtils.requireCurrentUser();if(SecurityUtils.isSuperAdmin())return true;if(!c.equals(u.getCollegeId()))return false;if(u.getAuthorities().stream().anyMatch(a->a.getAuthority().equals("ROLE_HOD"))){return staff.findByUserId(u.getId()).map(x->x.getDepartment()!=null&&d.equals(x.getDepartment().getId())).orElse(false);}return true;} private String up(String s){return s.trim().toUpperCase(Locale.ROOT);}
}
