package com.jadhavr.erp.timetable.service;
import com.jadhavr.erp.academic.entity.AcademicModels.*; import com.jadhavr.erp.attendance.entity.AttendanceModels.*; import com.jadhavr.erp.attendance.repository.*;
import com.jadhavr.erp.auth.security.SecurityUtils; import com.jadhavr.erp.college.entity.College; import com.jadhavr.erp.common.exception.*;
import com.jadhavr.erp.timetable.dto.TimetableDtos.*; import com.jadhavr.erp.timetable.entity.TimetableModels.*; import com.jadhavr.erp.timetable.repository.*; import com.jadhavr.erp.user.entity.User;
import jakarta.persistence.EntityManager; import jakarta.transaction.Transactional; import org.springframework.stereotype.Service; import java.time.DayOfWeek; import java.time.LocalDate; import java.time.LocalDateTime; import java.util.*;
@Service
public class TimetableService {
 private final EntityManager em; private final TimetableRepository tables; private final TimetableEntryRepository entries; private final AttendanceSessionRepository sessions; private final AuditLogRepository audits;
 public TimetableService(EntityManager em,TimetableRepository t,TimetableEntryRepository e,AttendanceSessionRepository s,AuditLogRepository a){this.em=em;tables=t;entries=e;sessions=s;audits=a;}
 private Long tenant(){Long id=SecurityUtils.requireCurrentUser().getCollegeId();if(id==null)throw new BadRequestException("Institution is required");return id;} private User actor(){return em.getReference(User.class,SecurityUtils.getCurrentUserId());}
 private <T extends TenantEntity>T owned(Class<T> c,Long id){T x=em.find(c,id);if(x==null||!tenant().equals(x.getCollege().getId()))throw new ResourceNotFoundException(c.getSimpleName()+" not found");return x;}
 private Timetable table(Long id){return tables.findByIdAndCollegeId(id,tenant()).orElseThrow(()->new ResourceNotFoundException("Timetable not found"));}
 @Transactional public TimetableResponse create(CreateTimetableRequest r){Timetable t=new Timetable();t.setCollege(em.getReference(College.class,tenant()));t.setAcademicYear(owned(AcademicYear.class,r.academicYearId()));t.setAcademicTerm(owned(AcademicTerm.class,r.academicTermId()));t.setAcademicClass(owned(AcademicClass.class,r.classId()));t.setSection(owned(Section.class,r.sectionId()));if(!t.getSection().getAcademicClass().getId().equals(t.getAcademicClass().getId()))throw new BadRequestException("Section does not belong to class");t.setWeekStart(r.weekStart().with(java.time.temporal.TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY)));t.setCreatedBy(actor());tables.save(t);audit("CREATE","Timetable",t.getId(),"Draft timetable created");return map(t);}
 @Transactional public EntryResponse addEntry(Long timetableId,EntryRequest r){Timetable t=table(timetableId);if(t.getStatus()!=TimetableStatus.DRAFT)throw new BadRequestException("Only draft timetables can be edited");Period p=owned(Period.class,r.periodId());PeriodType type;try{type=PeriodType.valueOf(r.type().toUpperCase(Locale.ROOT));}catch(Exception ex){throw new BadRequestException("Invalid entry type");}
  TimetableEntry e=new TimetableEntry();e.setCollege(t.getCollege());e.setTimetable(t);e.setDayOfWeek(r.dayOfWeek());e.setPeriod(p);e.setType(type);e.setCreatedBy(actor());
  if(type!=PeriodType.BREAK){if(r.subjectId()==null||r.teacherId()==null||r.roomId()==null)throw new BadRequestException("Subject, teacher and room are required");Subject subject=owned(Subject.class,r.subjectId());Room room=owned(Room.class,r.roomId());User teacher=em.find(User.class,r.teacherId());if(teacher==null||teacher.getCollege()==null||!tenant().equals(teacher.getCollege().getId()))throw new ResourceNotFoundException("Teacher not found");Long valid=em.createQuery("select count(a) from "+TeacherSubjectAssignment.class.getSimpleName()+" a where a.college.id=:c and a.teacher.id=:u and a.subject.id=:s and a.academicClass.id=:cl and a.section.id=:se",Long.class).setParameter("c",tenant()).setParameter("u",teacher.getId()).setParameter("s",subject.getId()).setParameter("cl",t.getAcademicClass().getId()).setParameter("se",t.getSection().getId()).getSingleResult();if(valid==0)throw new BadRequestException("Teacher is not assigned to this subject and class");
   List<TimetableEntry> conflicts=entries.conflicts(tenant(),r.dayOfWeek(),p.getStartTime(),p.getEndTime(),teacher.getId(),room.getId(),t.getAcademicClass().getId(),t.getSection().getId());if(!conflicts.isEmpty())throw new BadRequestException(conflictMessage(conflicts.get(0),teacher,room,t));e.setSubject(subject);e.setTeacher(teacher);e.setRoom(room);
  } else {List<TimetableEntry> same=entries.findByTimetableIdAndCollegeIdOrderByDayOfWeekAscPeriodPeriodNumberAsc(t.getId(),tenant());if(same.stream().anyMatch(x->x.getDayOfWeek()==r.dayOfWeek()&&x.getPeriod().getId().equals(p.getId())))throw new BadRequestException("Duplicate period for this class");}
  entries.save(e);audit("CREATE","TimetableEntry",e.getId(),"Entry added");return map(e);}
 @Transactional public TimetableResponse publish(Long id){Timetable t=table(id);if(t.getStatus()!=TimetableStatus.DRAFT)throw new BadRequestException("Only draft timetables can be published");List<TimetableEntry> all=entries.findByTimetableIdAndCollegeIdOrderByDayOfWeekAscPeriodPeriodNumberAsc(id,tenant());if(all.isEmpty())throw new BadRequestException("Cannot publish an empty timetable");t.setStatus(TimetableStatus.PUBLISHED);t.setPublishedBy(actor());t.setPublishedAt(LocalDateTime.now());generateSessions(t,all);audit("PUBLISH","Timetable",id,"Published and attendance sessions generated");return map(t);}
 @Transactional public TimetableResponse archive(Long id){Timetable t=table(id);t.setStatus(TimetableStatus.ARCHIVED);audit("ARCHIVE","Timetable",id,"Timetable archived");return map(t);}
 @Transactional public TimetableResponse copy(CopyRequest r){Timetable src=table(r.sourceTimetableId());CreateTimetableRequest cr=new CreateTimetableRequest(src.getAcademicYear().getId(),r.targetTermId()==null?src.getAcademicTerm().getId():r.targetTermId(),src.getAcademicClass().getId(),src.getSection().getId(),r.targetWeekStart());TimetableResponse created=create(cr);Timetable target=table(created.id());for(TimetableEntry old:entries.findByTimetableIdAndCollegeIdOrderByDayOfWeekAscPeriodPeriodNumberAsc(src.getId(),tenant())){TimetableEntry n=new TimetableEntry();n.setCollege(target.getCollege());n.setTimetable(target);n.setDayOfWeek(old.getDayOfWeek());n.setPeriod(old.getPeriod());n.setSubject(old.getSubject());n.setTeacher(old.getTeacher());n.setRoom(old.getRoom());n.setType(old.getType());n.setCreatedBy(actor());entries.save(n);}audit("COPY","Timetable",target.getId(),"Copied from "+src.getId());return map(target);}
 public List<TimetableResponse> list(){List<Timetable> result=tables.findByCollegeIdOrderByWeekStartDesc(tenant());Long user=SecurityUtils.getCurrentUserId();if(SecurityUtils.hasRole("SUBJECT_TEACHER")||SecurityUtils.hasRole("CLASS_TEACHER"))result=result.stream().filter(t->entries.findByTimetableIdAndCollegeIdOrderByDayOfWeekAscPeriodPeriodNumberAsc(t.getId(),tenant()).stream().anyMatch(e->e.getTeacher()!=null&&e.getTeacher().getId().equals(user))).toList();if(SecurityUtils.hasRole("STUDENT")){List<Long> sections=em.createQuery("select e.section.id from "+StudentEnrollment.class.getSimpleName()+" e where e.college.id=:c and e.student.user.id=:u and e.active=true",Long.class).setParameter("c",tenant()).setParameter("u",user).getResultList();result=result.stream().filter(t->sections.contains(t.getSection().getId())&&t.getStatus()==TimetableStatus.PUBLISHED).toList();}return result.stream().map(this::map).toList();}
 private void generateSessions(Timetable t,List<TimetableEntry> all){LocalDate from=t.getAcademicTerm().getStartDate(),to=t.getAcademicTerm().getEndDate();Set<LocalDate> holidays=new HashSet<>(em.createQuery("select h.date from "+Holiday.class.getSimpleName()+" h where h.college.id=:c and h.date between :f and :t",LocalDate.class).setParameter("c",tenant()).setParameter("f",from).setParameter("t",to).getResultList());for(TimetableEntry e:all){if(e.getType()==PeriodType.BREAK)continue;for(LocalDate d=from;!d.isAfter(to);d=d.plusDays(1)){if(d.getDayOfWeek()!=e.getDayOfWeek()||holidays.contains(d)||sessions.existsByCollegeIdAndTimetableEntryIdAndSessionDate(tenant(),e.getId(),d))continue;AttendanceSession s=new AttendanceSession();s.setCollege(t.getCollege());s.setTimetableEntry(e);s.setSessionDate(d);s.setAssignedTeacher(e.getTeacher());s.setLockAt(LocalDateTime.of(d,e.getPeriod().getEndTime()).plusHours(24));sessions.save(s);}}}
 private String conflictMessage(TimetableEntry c,User teacher,Room room,Timetable t){if(c.getTeacher()!=null&&c.getTeacher().getId().equals(teacher.getId()))return "Teacher time conflict";if(c.getRoom()!=null&&c.getRoom().getId().equals(room.getId()))return "Room time conflict";return "Class time conflict";}
 private TimetableResponse map(Timetable t){return new TimetableResponse(t.getId(),t.getAcademicYear().getName(),t.getAcademicTerm().getName(),t.getAcademicClass().getId(),t.getAcademicClass().getName(),t.getSection().getId(),t.getSection().getName(),t.getWeekStart(),t.getStatus().name(),entries.findByTimetableIdAndCollegeIdOrderByDayOfWeekAscPeriodPeriodNumberAsc(t.getId(),tenant()).stream().map(this::map).toList());}
 private EntryResponse map(TimetableEntry e){return new EntryResponse(e.getId(),e.getDayOfWeek(),e.getPeriod().getPeriodNumber(),e.getPeriod().getStartTime(),e.getPeriod().getEndTime(),e.getType().name(),e.getSubject()==null?null:e.getSubject().getId(),e.getSubject()==null?null:e.getSubject().getName(),e.getTeacher()==null?null:e.getTeacher().getId(),e.getTeacher()==null?null:e.getTeacher().getFullName(),e.getRoom()==null?null:e.getRoom().getId(),e.getRoom()==null?null:e.getRoom().getName());}
 private void audit(String action,String entity,Long id,String details){AuditLog a=new AuditLog();a.setCollege(em.getReference(College.class,tenant()));a.setActor(actor());a.setAction(action);a.setEntityType(entity);a.setEntityId(id);a.setDetails(details);audits.save(a);}
}
