package com.jadhavr.erp.timetable.service;
import com.jadhavr.erp.academic.entity.AcademicModels.*; import com.jadhavr.erp.attendance.entity.AttendanceModels.*; import com.jadhavr.erp.attendance.repository.*;
import com.jadhavr.erp.academic.enums.AcademicStatus; import com.jadhavr.erp.academic.enums.SubjectStatus; import com.jadhavr.erp.auth.security.SecurityUtils; import com.jadhavr.erp.college.entity.College; import com.jadhavr.erp.common.exception.*;
import com.jadhavr.erp.staff.entity.StaffProfile; import com.jadhavr.erp.timetable.dto.TimetableDtos.*; import com.jadhavr.erp.timetable.entity.TimetableModels.*; import com.jadhavr.erp.timetable.repository.*; import com.jadhavr.erp.user.entity.User;
import jakarta.persistence.EntityManager; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.DayOfWeek; import java.time.LocalDate; import java.time.LocalDateTime; import java.util.*;
@Service
public class TimetableService {
 private final EntityManager em; private final TimetableRepository tables; private final TimetableEntryRepository entries; private final AttendanceSessionRepository sessions; private final AuditLogRepository audits;
 public TimetableService(EntityManager em,TimetableRepository t,TimetableEntryRepository e,AttendanceSessionRepository s,AuditLogRepository a){this.em=em;tables=t;entries=e;sessions=s;audits=a;}
 private Long tenant(){Long id=SecurityUtils.requireCurrentUser().getCollegeId();if(id==null)throw new BadRequestException("Institution is required");return id;} private User actor(){return em.getReference(User.class,SecurityUtils.getCurrentUserId());}
 private <T extends TenantEntity>T owned(Class<T> c,Long id){T x=em.find(c,id);if(x==null||!tenant().equals(x.getCollege().getId()))throw new ResourceNotFoundException(c.getSimpleName()+" not found");return x;}
 private Timetable table(Long id){return tables.findByIdAndCollegeId(id,tenant()).orElseThrow(()->new ResourceNotFoundException("Timetable not found"));}
 @Transactional public TimetableResponse create(CreateTimetableRequest r){Timetable t=new Timetable();t.setCollege(em.getReference(College.class,tenant()));Long ayId=r.academicYearId();Long atId=r.academicTermId();if(ayId==null||ayId==0){List<AcademicYear> yrs=em.createQuery("select y from ManagedAcademicYear y where y.college.id=:c and y.active=true order by y.startDate desc",AcademicYear.class).setParameter("c",tenant()).getResultList();if(yrs.isEmpty())throw new BadRequestException("No active academic year found. Please create an academic year first.");ayId=yrs.get(0).getId();}if(atId==null||atId==0){List<AcademicTerm> ts=em.createQuery("select t from ManagedAcademicTerm t where t.academicYear.id=:y order by t.startDate desc",AcademicTerm.class).setParameter("y",ayId).getResultList();if(ts.isEmpty())throw new BadRequestException("No academic term found for this year. Please create an academic term first.");atId=ts.get(0).getId();}t.setAcademicYear(owned(AcademicYear.class,ayId));t.setAcademicTerm(owned(AcademicTerm.class,atId));t.setAcademicClass(owned(AcademicClass.class,r.classId()));t.setSection(owned(Section.class,r.sectionId()));if(!t.getSection().getAcademicClass().getId().equals(t.getAcademicClass().getId()))throw new BadRequestException("Section does not belong to class");t.setWeekStart(r.weekStart().with(java.time.temporal.TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY)));t.setCreatedBy(actor());tables.save(t);audit("CREATE","Timetable",t.getId(),"Draft timetable created");return map(t);}
 @Transactional public EntryResponse addEntry(Long timetableId,EntryRequest r){Timetable t=table(timetableId);if(t.getStatus()!=TimetableStatus.DRAFT)throw new BadRequestException("Only draft timetables can be edited");Period p=owned(Period.class,r.periodId());PeriodType type;try{type=PeriodType.valueOf(r.type().toUpperCase(Locale.ROOT));}catch(Exception ex){throw new BadRequestException("Invalid entry type");}
  TimetableEntry e=new TimetableEntry();e.setCollege(t.getCollege());e.setTimetable(t);e.setDayOfWeek(r.dayOfWeek());e.setPeriod(p);e.setType(type);e.setCreatedBy(actor());
  if(type!=PeriodType.BREAK){if(r.subjectId()==null||r.teacherId()==null)throw new BadRequestException("Subject and teacher are required");Subject subject=owned(Subject.class,r.subjectId());User teacher=em.find(User.class,r.teacherId());if(teacher==null||teacher.getCollege()==null||!tenant().equals(teacher.getCollege().getId()))throw new ResourceNotFoundException("Teacher not found");StaffProfile teacherProfile=em.createQuery("select sp from StaffProfile sp where sp.user.id=:u",StaffProfile.class).setParameter("u",teacher.getId()).getResultStream().findFirst().orElseThrow(()->new ResourceNotFoundException("Teacher profile not found"));Long valid=em.createQuery("select count(sta) from SubjectTeacherAssignment sta where sta.subject.id=:s and sta.teacher.id=:staffId and sta.status=:status and sta.subject.academicClass.id=:cl",Long.class).setParameter("s",r.subjectId()).setParameter("staffId",teacherProfile.getId()).setParameter("status",AcademicStatus.ACTIVE).setParameter("cl",t.getAcademicClass().getId()).getSingleResult();if(valid==0)throw new BadRequestException("Teacher is not assigned to this subject and class");
   Room room=null;if(r.roomId()!=null)room=owned(Room.class,r.roomId());List<TimetableEntry> conflicts=entries.conflicts(tenant(),r.dayOfWeek(),p.getStartTime(),p.getEndTime(),teacher.getId(),room==null?null:room.getId(),t.getAcademicClass().getId(),t.getSection().getId());if(!conflicts.isEmpty())throw new BadRequestException(conflictMessage(conflicts.get(0),teacher,room,t));e.setSubject(subject);e.setTeacher(teacher);e.setRoom(room);
  } else {List<TimetableEntry> same=entries.findByTimetableIdAndCollegeIdOrderByDayOfWeekAscPeriodPeriodNumberAsc(t.getId(),tenant());if(same.stream().anyMatch(x->x.getDayOfWeek()==r.dayOfWeek()&&x.getPeriod().getId().equals(p.getId())))throw new BadRequestException("Duplicate period for this class");}
  entries.save(e);audit("CREATE","TimetableEntry",e.getId(),"Entry added");return map(e);}
 @Transactional public EntryResponse updateEntry(Long timetableId,Long entryId,UpdateEntryRequest r){Timetable t=table(timetableId);if(t.getStatus()!=TimetableStatus.DRAFT)throw new BadRequestException("Only draft timetables can be edited");TimetableEntry e=entries.findByIdAndCollegeId(entryId,tenant()).orElseThrow(()->new ResourceNotFoundException("Entry not found"));if(!e.getTimetable().getId().equals(timetableId))throw new BadRequestException("Entry does not belong to this timetable");
  if(r.type()!=null){PeriodType type=PeriodType.valueOf(r.type().toUpperCase(Locale.ROOT));e.setType(type);}
  if(e.getType()!=PeriodType.BREAK){if(r.subjectId()!=null)e.setSubject(owned(Subject.class,r.subjectId()));if(r.teacherId()!=null){User teacher=em.find(User.class,r.teacherId());if(teacher==null||teacher.getCollege()==null||!tenant().equals(teacher.getCollege().getId()))throw new ResourceNotFoundException("Teacher not found");e.setTeacher(teacher);}if(r.roomId()!=null)e.setRoom(owned(Room.class,r.roomId()));if(e.getSubject()!=null&&e.getTeacher()!=null){List<TimetableEntry> conflicts=entries.conflicts(tenant(),e.getDayOfWeek(),e.getPeriod().getStartTime(),e.getPeriod().getEndTime(),e.getTeacher().getId(),e.getRoom()==null?null:e.getRoom().getId(),t.getAcademicClass().getId(),t.getSection().getId());conflicts=conflicts.stream().filter(c->!c.getId().equals(entryId)).toList();if(!conflicts.isEmpty())throw new BadRequestException(conflictMessage(conflicts.get(0),e.getTeacher(),e.getRoom(),t));}}
  entries.save(e);audit("UPDATE","TimetableEntry",e.getId(),"Entry updated");return map(e);}
 @Transactional public void deleteEntry(Long timetableId,Long entryId){Timetable t=table(timetableId);if(t.getStatus()!=TimetableStatus.DRAFT)throw new BadRequestException("Only draft timetables can be edited");TimetableEntry e=entries.findByIdAndCollegeId(entryId,tenant()).orElseThrow(()->new ResourceNotFoundException("Entry not found"));if(!e.getTimetable().getId().equals(timetableId))throw new BadRequestException("Entry does not belong to this timetable");entries.delete(e);audit("DELETE","TimetableEntry",entryId,"Entry deleted");}
 @Transactional public TimetableResponse publish(Long id){Timetable t=table(id);if(t.getStatus()!=TimetableStatus.DRAFT)throw new BadRequestException("Only draft timetables can be published");List<TimetableEntry> all=entries.findByTimetableIdAndCollegeIdOrderByDayOfWeekAscPeriodPeriodNumberAsc(id,tenant());if(all.isEmpty())throw new BadRequestException("Cannot publish an empty timetable");t.setStatus(TimetableStatus.PUBLISHED);t.setPublishedBy(actor());t.setPublishedAt(LocalDateTime.now());generateSessions(t,all);audit("PUBLISH","Timetable",id,"Published and attendance sessions generated");return map(t);}
 @Transactional public TimetableResponse archive(Long id){Timetable t=table(id);t.setStatus(TimetableStatus.ARCHIVED);audit("ARCHIVE","Timetable",id,"Timetable archived");return map(t);}
 @Transactional public TimetableResponse copy(CopyRequest r){Timetable src=table(r.sourceTimetableId());CreateTimetableRequest cr=new CreateTimetableRequest(src.getAcademicYear().getId(),r.targetTermId()==null?src.getAcademicTerm().getId():r.targetTermId(),src.getAcademicClass().getId(),src.getSection().getId(),r.targetWeekStart());TimetableResponse created=create(cr);Timetable target=table(created.id());for(TimetableEntry old:entries.findByTimetableIdAndCollegeIdOrderByDayOfWeekAscPeriodPeriodNumberAsc(src.getId(),tenant())){TimetableEntry n=new TimetableEntry();n.setCollege(target.getCollege());n.setTimetable(target);n.setDayOfWeek(old.getDayOfWeek());n.setPeriod(old.getPeriod());n.setSubject(old.getSubject());n.setTeacher(old.getTeacher());n.setRoom(old.getRoom());n.setType(old.getType());n.setCreatedBy(actor());entries.save(n);}audit("COPY","Timetable",target.getId(),"Copied from "+src.getId());return map(target);}
 @Transactional public TimetableResponse copyDay(Long timetableId,CopyDayRequest r){Timetable t=table(timetableId);if(t.getStatus()!=TimetableStatus.DRAFT)throw new BadRequestException("Only draft timetables can be edited");List<TimetableEntry> all=entries.findByTimetableIdAndCollegeIdOrderByDayOfWeekAscPeriodPeriodNumberAsc(timetableId,tenant());List<TimetableEntry> sourceEntries=all.stream().filter(e->e.getDayOfWeek()==r.sourceDay()).toList();if(sourceEntries.isEmpty())throw new BadRequestException("No entries found for "+r.sourceDay());entries.deleteAll(all.stream().filter(e->e.getDayOfWeek()==r.targetDay()).toList());for(TimetableEntry old:sourceEntries){TimetableEntry n=new TimetableEntry();n.setCollege(t.getCollege());n.setTimetable(t);n.setDayOfWeek(r.targetDay());n.setPeriod(old.getPeriod());n.setSubject(old.getSubject());n.setTeacher(old.getTeacher());n.setRoom(old.getRoom());n.setType(old.getType());n.setCreatedBy(actor());entries.save(n);}audit("COPY_DAY","Timetable",timetableId,"Copied "+r.sourceDay()+" to "+r.targetDay());return map(t);}
 @Transactional public TimetableResponse copyWeek(Long timetableId,CopyWeekRequest r){Timetable src=table(timetableId);Timetable target=table(r.targetTimetableId());if(target.getStatus()!=TimetableStatus.DRAFT)throw new BadRequestException("Target timetable must be draft");List<TimetableEntry> srcEntries=entries.findByTimetableIdAndCollegeIdOrderByDayOfWeekAscPeriodPeriodNumberAsc(src.getId(),tenant());List<TimetableEntry> tgtEntries=entries.findByTimetableIdAndCollegeIdOrderByDayOfWeekAscPeriodPeriodNumberAsc(target.getId(),tenant());entries.deleteAll(tgtEntries);for(TimetableEntry old:srcEntries){TimetableEntry n=new TimetableEntry();n.setCollege(target.getCollege());n.setTimetable(target);n.setDayOfWeek(old.getDayOfWeek());n.setPeriod(old.getPeriod());n.setSubject(old.getSubject());n.setTeacher(old.getTeacher());n.setRoom(old.getRoom());n.setType(old.getType());n.setCreatedBy(actor());entries.save(n);}audit("COPY_WEEK","Timetable",timetableId,"Copied to timetable "+r.targetTimetableId());return map(target);}
 public List<TimetableResponse> list(){List<Timetable> result=tables.findByCollegeIdOrderByWeekStartDesc(tenant());Long user=SecurityUtils.getCurrentUserId();if(SecurityUtils.hasRole("SUBJECT_TEACHER"))result=result.stream().filter(t->entries.findByTimetableIdAndCollegeIdOrderByDayOfWeekAscPeriodPeriodNumberAsc(t.getId(),tenant()).stream().anyMatch(e->e.getTeacher()!=null&&e.getTeacher().getId().equals(user))).toList();if(SecurityUtils.hasRole("CLASS_TEACHER")){List<Long> sections=em.createQuery("select s.id from Section s where s.classTeacher.user.id=:u",Long.class).setParameter("u",user).getResultList();result=result.stream().filter(t->sections.contains(t.getSection().getId())).toList();}if(SecurityUtils.hasRole("STUDENT")){List<Long> sections=em.createQuery("select e.section.id from ManagedStudentEnrollment e where e.college.id=:c and e.student.user.id=:u and e.active=true",Long.class).setParameter("c",tenant()).setParameter("u",user).getResultList();result=result.stream().filter(t->sections.contains(t.getSection().getId())&&t.getStatus()==TimetableStatus.PUBLISHED).toList();}return result.stream().map(this::map).toList();}
 @Transactional(readOnly=true) public List<EntryResponse> search(SearchRequest r){Long t=tenant();List<TimetableEntry> results;if(r.query()!=null&&!r.query().isBlank()){results=entries.search(t,r.query());}else{results=new ArrayList<>();for(Timetable tl:tables.findByCollegeIdOrderByWeekStartDesc(t)){results.addAll(entries.findByTimetableIdAndCollegeIdOrderByDayOfWeekAscPeriodPeriodNumberAsc(tl.getId(),t));}}
  if(r.dayOfWeek()!=null)results=results.stream().filter(e->e.getDayOfWeek()==r.dayOfWeek()).toList();if(r.divisionId()!=null)results=results.stream().filter(e->e.getTimetable().getSection().getId().equals(r.divisionId())).toList();if(r.subject()!=null&&!r.subject().isBlank())results=results.stream().filter(e->e.getSubject()!=null&&e.getSubject().getName().toLowerCase().contains(r.subject().toLowerCase())).toList();if(r.teacher()!=null&&!r.teacher().isBlank())results=results.stream().filter(e->e.getTeacher()!=null&&e.getTeacher().getFullName().toLowerCase().contains(r.teacher().toLowerCase())).toList();if(r.room()!=null&&!r.room().isBlank())results=results.stream().filter(e->e.getRoom()!=null&&e.getRoom().getName().toLowerCase().contains(r.room().toLowerCase())).toList();return results.stream().map(this::map).toList();}
 @Transactional(readOnly=true) public Map<String,Object> mySection(){List<com.jadhavr.erp.academic.entity.Section> sections=em.createQuery("select s from Section s where s.classTeacher.user.id=:u",com.jadhavr.erp.academic.entity.Section.class).setParameter("u",SecurityUtils.getCurrentUserId()).getResultList();if(sections.isEmpty())throw new ResourceNotFoundException("No class assigned to you");com.jadhavr.erp.academic.entity.Section s=sections.get(0);List<AcademicYear> years=em.createQuery("select y from ManagedAcademicYear y where y.college.id=:c order by y.startDate desc",AcademicYear.class).setParameter("c",tenant()).getResultList();AcademicYear ay=years.isEmpty()?null:years.get(0);List<AcademicTerm> terms=ay==null?List.of():em.createQuery("select t from ManagedAcademicTerm t where t.academicYear.id=:y order by t.startDate",AcademicTerm.class).setParameter("y",ay.getId()).getResultList();AcademicTerm at=terms.isEmpty()?null:terms.get(0);Map<String,Object> r=new LinkedHashMap<>();r.put("sectionId",s.getId());r.put("classId",s.getAcademicClass().getId());r.put("courseYear",s.getAcademicClass().getName());r.put("yearName",s.getAcademicClass().getYearName().name());r.put("division",s.getName());r.put("divisionCode",s.getCode());r.put("academicYear",s.getAcademicYear());r.put("collegeId",s.getCollege().getId());r.put("departmentId",s.getDepartment().getId());r.put("departmentName",s.getDepartment().getName());if(ay!=null){r.put("academicYearId",ay.getId());r.put("academicYearName",ay.getName());}if(at!=null){r.put("academicTermId",at.getId());r.put("academicTermName",at.getName());}return r;}
 @Transactional(readOnly=true) public List<Map<String,Object>> mySectionSubjects(){com.jadhavr.erp.academic.entity.Section s=em.createQuery("select s from Section s where s.classTeacher.user.id=:u",com.jadhavr.erp.academic.entity.Section.class).setParameter("u",SecurityUtils.getCurrentUserId()).getResultStream().findFirst().orElseThrow(()->new ResourceNotFoundException("No class assigned to you"));return em.createQuery("select distinct ts.subject from SubjectTeacherAssignment ts where ts.subject.academicClass.id=:c and ts.status='ACTIVE'",com.jadhavr.erp.academic.entity.Subject.class).setParameter("c",s.getAcademicClass().getId()).getResultStream().map(sub->{Map<String,Object> m=new LinkedHashMap<>();m.put("id",sub.getId());m.put("name",sub.getName());m.put("code",sub.getCode());m.put("subjectType",sub.getSubjectType()!=null?sub.getSubjectType().name():null);return m;}).toList();}
 @Transactional(readOnly=true) public List<Map<String,Object>> sectionTeachers(Long subjectId){return em.createQuery("select distinct sp from StaffProfile sp join SubjectTeacherAssignment sta on sta.teacher.id=sp.id where sta.subject.id=:s and sta.status='ACTIVE'",com.jadhavr.erp.staff.entity.StaffProfile.class).setParameter("s",subjectId).getResultStream().map(sp->{Map<String,Object> m=new LinkedHashMap<>();m.put("id",sp.getId());m.put("fullName",sp.getFullName());m.put("email",sp.getEmail());return m;}).toList();}
 @Transactional(readOnly=true) public List<Map<String,Object>> availablePeriods(){return em.createQuery("select p from ManagedPeriod p where p.college.id=:c order by p.periodNumber",Period.class).setParameter("c",tenant()).getResultStream().map(p->{Map<String,Object> m=new LinkedHashMap<>();m.put("id",p.getId());m.put("periodNumber",p.getPeriodNumber());m.put("startTime",p.getStartTime().toString());m.put("endTime",p.getEndTime().toString());m.put("type",p.getType().name());return m;}).toList();}
 @Transactional(readOnly=true) public List<Map<String,Object>> availableRooms(){return em.createQuery("select r from ManagedRoom r where r.college.id=:c order by r.code",Room.class).setParameter("c",tenant()).getResultStream().map(r->{Map<String,Object> m=new LinkedHashMap<>();m.put("id",r.getId());m.put("code",r.getCode());m.put("name",r.getName());m.put("capacity",r.getCapacity());m.put("type",r.getType().name());return m;}).toList();}
 private void generateSessions(Timetable t,List<TimetableEntry> all){LocalDate from=t.getAcademicTerm().getStartDate(),to=t.getAcademicTerm().getEndDate();Set<LocalDate> holidays=new HashSet<>(em.createQuery("select h.date from ManagedHoliday h where h.college.id=:c and h.date between :f and :t",LocalDate.class).setParameter("c",tenant()).setParameter("f",from).setParameter("t",to).getResultList());for(TimetableEntry e:all){if(e.getType()==PeriodType.BREAK)continue;for(LocalDate d=from;!d.isAfter(to);d=d.plusDays(1)){if(d.getDayOfWeek()!=e.getDayOfWeek()||holidays.contains(d)||sessions.existsByCollegeIdAndTimetableEntryIdAndSessionDate(tenant(),e.getId(),d))continue;AttendanceSession s=new AttendanceSession();s.setCollege(t.getCollege());s.setTimetableEntry(e);s.setSessionDate(d);s.setAssignedTeacher(e.getTeacher());s.setLockAt(LocalDateTime.of(d,e.getPeriod().getEndTime()).plusHours(24));sessions.save(s);}}}
 private String conflictMessage(TimetableEntry c,User teacher,Room room,Timetable t){if(c.getTeacher()!=null&&c.getTeacher().getId().equals(teacher.getId()))return "Teacher already has a lecture at this time";if(c.getRoom()!=null&&room!=null&&c.getRoom().getId().equals(room.getId()))return "Room already occupied at this time";return "Division already has a lecture at this time";}
 private TimetableResponse map(Timetable t){return new TimetableResponse(t.getId(),t.getAcademicYear().getName(),t.getAcademicTerm().getName(),t.getAcademicClass().getId(),t.getAcademicClass().getName(),t.getSection().getId(),t.getSection().getName(),t.getWeekStart(),t.getStatus().name(),entries.findByTimetableIdAndCollegeIdOrderByDayOfWeekAscPeriodPeriodNumberAsc(t.getId(),tenant()).stream().map(this::map).toList());}
 private EntryResponse map(TimetableEntry e){return new EntryResponse(e.getId(),e.getDayOfWeek(),e.getPeriod().getPeriodNumber(),e.getPeriod().getStartTime(),e.getPeriod().getEndTime(),e.getType().name(),e.getSubject()==null?null:e.getSubject().getId(),e.getSubject()==null?null:e.getSubject().getName(),e.getTeacher()==null?null:e.getTeacher().getId(),e.getTeacher()==null?null:e.getTeacher().getFullName(),e.getRoom()==null?null:e.getRoom().getId(),e.getRoom()==null?null:e.getRoom().getName(),null,e.getCreatedBy()==null?null:e.getCreatedBy().getId(),e.getCreatedBy()==null?null:e.getCreatedBy().getFullName());}
 private void audit(String action,String entity,Long id,String details){AuditLog a=new AuditLog();a.setCollege(em.getReference(College.class,tenant()));a.setActor(actor());a.setAction(action);a.setEntityType(entity);a.setEntityId(id);a.setDetails(details);audits.save(a);}
}
