CREATE TABLE admission_document_requirements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    college_id BIGINT NOT NULL,
    document_key VARCHAR(60) NOT NULL,
    document_name VARCHAR(120) NOT NULL,
    required BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INTEGER NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_admission_document_requirement_college
        FOREIGN KEY (college_id) REFERENCES colleges(id),
    CONSTRAINT uk_admission_document_requirement_key
        UNIQUE (college_id, document_key),
    CONSTRAINT ck_admission_document_requirement_key
        CHECK (document_key ~ '^[A-Z][A-Z0-9_]{1,59}$'),
    CONSTRAINT ck_admission_document_requirement_name
        CHECK (CHAR_LENGTH(BTRIM(document_name)) BETWEEN 2 AND 120),
    CONSTRAINT ck_admission_document_requirement_order
        CHECK (display_order >= 0)
);

CREATE UNIQUE INDEX uk_admission_document_requirement_name
    ON admission_document_requirements(college_id, LOWER(document_name));

CREATE INDEX idx_admission_document_requirement_active_order
    ON admission_document_requirements(college_id, active, display_order, id);

INSERT INTO admission_document_requirements
    (college_id, document_key, document_name, required, active, display_order)
SELECT college.id, defaults.document_key, defaults.document_name,
       defaults.required, TRUE, defaults.display_order
FROM colleges college
CROSS JOIN (VALUES
    ('TENTH_MARKSHEET', '10th Marksheet', TRUE, 10),
    ('TWELFTH_MARKSHEET', '12th Marksheet', TRUE, 20),
    ('PROVISIONAL_CERTIFICATE', 'Provisional Certificate', TRUE, 30),
    ('TRANSFER_CERTIFICATE', 'Transfer Certificate', TRUE, 40),
    ('NATIONALITY_CERTIFICATE', 'Nationality Certificate', TRUE, 50),
    ('DOMICILE_CERTIFICATE', 'Domicile Certificate', TRUE, 60),
    ('AADHAAR_CARD', 'Aadhaar Card', TRUE, 70),
    ('GRADUATION_MARKSHEET', 'Graduation Marksheet', FALSE, 80),
    ('MIGRATION_CERTIFICATE', 'Migration Certificate', FALSE, 90),
    ('GAP_CERTIFICATE', 'Gap Certificate', FALSE, 100),
    ('ENTRANCE_SCORE_CARD', 'Entrance Score Card', FALSE, 110),
    ('CASTE_CERTIFICATE', 'Caste Certificate', FALSE, 120),
    ('CASTE_VALIDITY', 'Caste Validity', FALSE, 130),
    ('NON_CREAMY_LAYER_CERTIFICATE', 'Non-Creamy Layer Certificate', FALSE, 140),
    ('NAME_CHANGE_CERTIFICATE', 'Name Change Certificate', FALSE, 150),
    ('INCOME_CERTIFICATE', 'Income Certificate', FALSE, 160),
    ('FORM_O_MINORITY', 'Form O / Minority Certificate', FALSE, 170)
) AS defaults(document_key, document_name, required, display_order)
ON CONFLICT (college_id, document_key) DO NOTHING;
