CREATE TABLE lecture_substitutions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL,
    college_id bigint NOT NULL REFERENCES colleges(id),
    timetable_entry_id bigint NOT NULL REFERENCES weekly_timetable_entries(id),
    lecture_date date NOT NULL,
    original_teacher_id bigint NOT NULL REFERENCES staff_profiles(id),
    substitute_teacher_id bigint NOT NULL REFERENCES staff_profiles(id),
    substitute_subject_id bigint NOT NULL REFERENCES course_year_subjects(id),
    reason varchar(300) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'ACTIVE',
    cancelled_at timestamp,
    CONSTRAINT ck_lecture_substitution_status CHECK (status IN ('ACTIVE', 'CANCELLED')),
    CONSTRAINT ck_lecture_substitution_different_teacher CHECK (original_teacher_id <> substitute_teacher_id)
);

CREATE UNIQUE INDEX uk_lecture_substitution_active_entry_date
    ON lecture_substitutions(timetable_entry_id, lecture_date)
    WHERE status = 'ACTIVE';

CREATE INDEX idx_lecture_substitution_original_date
    ON lecture_substitutions(original_teacher_id, lecture_date, status);

CREATE INDEX idx_lecture_substitution_substitute_date
    ON lecture_substitutions(substitute_teacher_id, lecture_date, status);

CREATE INDEX idx_lecture_substitution_college_date
    ON lecture_substitutions(college_id, lecture_date, status);
