ALTER TABLE weekly_timetables
    ADD COLUMN IF NOT EXISTS review_status varchar(30) NOT NULL DEFAULT 'DRAFT',
    ADD COLUMN IF NOT EXISTS review_comment varchar(1000),
    ADD COLUMN IF NOT EXISTS submitted_at timestamp,
    ADD COLUMN IF NOT EXISTS reviewed_at timestamp;

CREATE TABLE IF NOT EXISTS subject_teacher_divisions (
    assignment_id bigint NOT NULL REFERENCES subject_teacher_assignments(id) ON DELETE CASCADE,
    section_id bigint NOT NULL REFERENCES course_year_divisions(id),
    PRIMARY KEY (assignment_id, section_id)
);

CREATE TABLE IF NOT EXISTS student_division_transfers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL,
    transferred_at timestamp NOT NULL,
    student_id bigint NOT NULL REFERENCES student_profiles(id),
    from_section_id bigint REFERENCES course_year_divisions(id),
    to_section_id bigint NOT NULL REFERENCES course_year_divisions(id),
    changed_by_id bigint NOT NULL REFERENCES staff_profiles(id)
);

CREATE TABLE IF NOT EXISTS class_teacher_assignment_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL,
    assigned_at timestamp NOT NULL,
    section_id bigint NOT NULL REFERENCES course_year_divisions(id),
    previous_teacher_id bigint REFERENCES staff_profiles(id),
    new_teacher_id bigint NOT NULL REFERENCES staff_profiles(id),
    assigned_by_id bigint NOT NULL REFERENCES staff_profiles(id)
);

CREATE INDEX IF NOT EXISTS idx_hod_transfer_department_time
    ON student_division_transfers(to_section_id, transferred_at DESC);
CREATE INDEX IF NOT EXISTS idx_hod_class_teacher_history_time
    ON class_teacher_assignment_history(section_id, assigned_at DESC);
CREATE INDEX IF NOT EXISTS idx_hod_timetable_review
    ON weekly_timetables(review_status, submitted_at DESC);
