CREATE TABLE IF NOT EXISTS teacher_notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL,
    teacher_id bigint NOT NULL REFERENCES staff_profiles(id),
    type varchar(40) NOT NULL,
    message varchar(500) NOT NULL,
    read_at timestamp
);

CREATE INDEX IF NOT EXISTS idx_teacher_notification_inbox
    ON teacher_notifications(teacher_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_teacher_notification_unread
    ON teacher_notifications(teacher_id, read_at);
