ALTER TABLE admission_forms
    ADD COLUMN IF NOT EXISTS course_year_id bigint;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_admission_course_year') THEN
        ALTER TABLE admission_forms ADD CONSTRAINT fk_admission_course_year
            FOREIGN KEY (course_year_id) REFERENCES course_years(id);
    END IF;
END $$;

ALTER TABLE admission_academic_records
    ADD COLUMN IF NOT EXISTS total_marks numeric(10,2),
    ADD COLUMN IF NOT EXISTS obtained_marks numeric(10,2);

ALTER TABLE admission_academic_records DROP CONSTRAINT IF EXISTS admission_academic_records_marks_check;
ALTER TABLE admission_academic_records ADD CONSTRAINT admission_academic_records_marks_check CHECK (
    (total_marks IS NULL AND obtained_marks IS NULL)
    OR (total_marks > 0 AND obtained_marks >= 0 AND obtained_marks <= total_marks)
);

CREATE TABLE IF NOT EXISTS admission_documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_form_id bigint NOT NULL REFERENCES admission_forms(id),
    document_type varchar(60) NOT NULL,
    storage_name varchar(220) NOT NULL,
    original_filename varchar(255) NOT NULL,
    content_type varchar(100) NOT NULL,
    file_size bigint NOT NULL,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL,
    CONSTRAINT uk_admission_document_type UNIQUE (admission_form_id, document_type),
    CONSTRAINT admission_document_size_check CHECK (file_size > 0 AND file_size <= 5242880)
);

CREATE INDEX IF NOT EXISTS idx_admission_documents_admission ON admission_documents(admission_form_id);
