package com.collegeerp.erp.fee.service;

import com.collegeerp.erp.academic.entity.StudentSectionEnrollment;
import com.collegeerp.erp.academic.enums.AcademicStatus;
import com.collegeerp.erp.academic.repository.StudentSectionEnrollmentRepository;
import com.collegeerp.erp.auth.security.SecurityUtils;
import com.collegeerp.erp.common.exception.*;
import com.collegeerp.erp.fee.dto.FeeOfficerDtos.*;
import com.collegeerp.erp.fee.dto.FeeTransactionResponse;
import com.collegeerp.erp.fee.entity.*;
import com.collegeerp.erp.fee.enums.*;
import com.collegeerp.erp.fee.repository.*;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.*;
import java.time.*;
import java.time.temporal.ChronoUnit;
import java.util.*;
import java.util.function.Function;
import java.util.stream.Collectors;

@Service @Transactional(readOnly=true)
public class FeeOfficerWorkspaceService {
    private final StudentFeeAccountRepository accounts;private final FeePaymentRepository payments;private final FeeTransactionRepository transactions;private final StudentSectionEnrollmentRepository enrollments;
    public FeeOfficerWorkspaceService(StudentFeeAccountRepository a,FeePaymentRepository p,FeeTransactionRepository t,StudentSectionEnrollmentRepository e){accounts=a;payments=p;transactions=t;enrollments=e;}

    public Workspace workspace(String search,Long departmentId,String academicYear,Long courseYearId,String accountStatus,String paymentMode,String paymentStatus,int page,int size){
        Long collegeId=college();List<StudentFeeAccount> accountRows=accounts.findByCollegeId(collegeId);List<FeePayment> paymentRows=payments.findByCollegeId(collegeId);Map<Long,StudentSectionEnrollment> enrollmentByStudent=enrollmentMap(accountRows);
        List<AccountRow> filteredAccounts=accountRows.stream().filter(a->accountMatch(a,enrollmentByStudent.get(a.getStudent().getId()),search,departmentId,academicYear,courseYearId,accountStatus)).map(a->account(a,enrollmentByStudent.get(a.getStudent().getId()),paymentRows)).sorted(Comparator.comparing(AccountRow::student)).toList();
        int safeSize=Math.min(Math.max(size,1),100),safePage=Math.max(page,0),from=Math.min(safePage*safeSize,filteredAccounts.size()),to=Math.min(from+safeSize,filteredAccounts.size());AccountPage accountPage=new AccountPage(filteredAccounts.subList(from,to),filteredAccounts.size(),safePage,(int)Math.ceil(filteredAccounts.size()/(double)safeSize));
        List<PaymentRow> allPayments=paymentRows.stream().filter(p->paymentMatch(p,enrollmentByStudent.get(p.getStudent().getId()),search,departmentId,academicYear,courseYearId,paymentMode,paymentStatus)).map(p->payment(p,enrollmentByStudent.get(p.getStudent().getId()),paymentRows)).sorted(Comparator.comparing(PaymentRow::submittedAt).reversed()).toList();
        LocalDate today=LocalDate.now();LocalDateTime start=today.atStartOfDay();BigDecimal todayAmount=sum(paymentRows.stream().filter(p->p.getStatus()==PaymentStatus.VERIFIED&&p.getVerifiedAt()!=null&&!p.getVerifiedAt().isBefore(start)).toList());BigDecimal monthAmount=sum(paymentRows.stream().filter(p->p.getStatus()==PaymentStatus.VERIFIED&&p.getVerifiedAt()!=null&&!p.getVerifiedAt().isBefore(today.withDayOfMonth(1).atStartOfDay())).toList());
        List<FeePayment> verifiedRaw=paymentRows.stream().filter(p->p.getStatus()==PaymentStatus.VERIFIED).toList();double avgMinutes=verifiedRaw.stream().filter(p->p.getVerifiedAt()!=null&&p.getSubmittedAt()!=null).mapToLong(p->ChronoUnit.MINUTES.between(p.getSubmittedAt(),p.getVerifiedAt())).average().orElse(0);
        Summary summary=new Summary(accountRows.size(),count(paymentRows,PaymentStatus.PENDING),count(paymentRows,PaymentStatus.VERIFIED),count(paymentRows,PaymentStatus.REJECTED),todayAmount,monthAmount,accountRows.stream().map(StudentFeeAccount::getRemainingAmount).reduce(BigDecimal.ZERO,BigDecimal::add),paymentRows.stream().filter(p->p.getStatus()==PaymentStatus.PENDING&&p.getSubmittedAt().toLocalDate().equals(today)).count(),accountRows.stream().filter(a->a.getStatus()==FeeAccountStatus.PAID).count(),accountRows.stream().filter(a->a.getStatus()==FeeAccountStatus.PARTIALLY_PAID).count(),Math.round(avgMinutes*10)/10.0);
        List<DueRow> dues=accountRows.stream().filter(a->a.getRemainingAmount().signum()>0).map(a->due(a,paymentRows)).sorted(Comparator.comparing(DueRow::dueDate)).toList();
        List<PaymentRow> pending=allPayments.stream().filter(p->p.status().equals(PaymentStatus.PENDING.name())||p.status().equals(PaymentStatus.RESUBMISSION_REQUESTED.name())).toList();List<PaymentRow> verified=allPayments.stream().filter(p->p.status().equals(PaymentStatus.VERIFIED.name())).toList();List<PaymentRow> rejected=allPayments.stream().filter(p->p.status().equals(PaymentStatus.REJECTED.name())).toList();
        List<FilterOption> departmentOptions=accountRows.stream().collect(Collectors.toMap(a->a.getDepartment().getId(),a->a.getDepartment().getName(),(a,b)->a)).entrySet().stream().map(e->new FilterOption(e.getKey(),e.getValue())).sorted(Comparator.comparing(FilterOption::label)).toList();
        List<FilterOption> courseOptions=enrollmentByStudent.values().stream().map(StudentSectionEnrollment::getAcademicClass).collect(Collectors.toMap(c->c.getId(),c->c.getName(),(a,b)->a)).entrySet().stream().map(e->new FilterOption(e.getKey(),e.getValue())).sorted(Comparator.comparing(FilterOption::label)).toList();
        List<String> yearOptions=accountRows.stream().map(StudentFeeAccount::getAcademicYear).distinct().sorted(Comparator.reverseOrder()).toList();
        return new Workspace(summary,accountPage,pending,verified,rejected,allPayments,dues,daily(paymentRows,today),monthly(paymentRows,today),departments(paymentRows),List.of(new MoneyPoint("Collected",accountRows.stream().map(StudentFeeAccount::getPaidAmount).reduce(BigDecimal.ZERO,BigDecimal::add)),new MoneyPoint("Pending",accountRows.stream().map(StudentFeeAccount::getRemainingAmount).reduce(BigDecimal.ZERO,BigDecimal::add))),verified.stream().limit(8).toList(),rejected.stream().limit(8).toList(),allPayments.stream().sorted(Comparator.comparing(PaymentRow::amount).reversed()).limit(8).toList(),dues.stream().limit(10).toList(),departmentOptions,courseOptions,yearOptions);
    }

    public AccountDetail accountDetail(Long id){Long collegeId=college();StudentFeeAccount a=accounts.findById(id).orElseThrow(()->new ResourceNotFoundException("Fee account not found"));if(!a.getCollege().getId().equals(collegeId))throw new AccessDeniedException("Fee account is outside your college");List<FeePayment> all=payments.findByStudentFeeAccountIdOrderByCreatedAtDesc(id);StudentSectionEnrollment enrollment=enrollmentMap(List.of(a)).get(a.getStudent().getId());List<PaymentRow> paymentRows=all.stream().map(p->payment(p,enrollment,all)).toList();List<FeeTransactionResponse> tx=transactions.findByStudentFeeAccountIdOrderByCreatedAtDesc(id).stream().map(this::transaction).toList();return new AccountDetail(account(a,enrollment,all),paymentRows,tx,installments(a),paymentRows.stream().filter(p->p.receiptNumber()!=null).map(PaymentRow::receiptNumber).toList());}

    private Map<Long,StudentSectionEnrollment> enrollmentMap(List<StudentFeeAccount> rows){List<Long> ids=rows.stream().map(a->a.getStudent().getId()).distinct().toList();if(ids.isEmpty())return Map.of();return enrollments.findByStudentIdInAndStatus(ids,AcademicStatus.ACTIVE).stream().collect(Collectors.toMap(e->e.getStudent().getId(),Function.identity(),(a,b)->a));}
    private boolean accountMatch(StudentFeeAccount a,StudentSectionEnrollment e,String search,Long departmentId,String year,Long courseYearId,String status){String q=search==null?"":search.trim().toLowerCase(Locale.ROOT);return(q.isEmpty()||List.of(a.getStudent().getFullName(),a.getStudent().getAdmissionNumber()).stream().anyMatch(v->v.toLowerCase(Locale.ROOT).contains(q)))&&(departmentId==null||a.getDepartment().getId().equals(departmentId))&&(year==null||year.isBlank()||a.getAcademicYear().equals(year))&&(courseYearId==null||e!=null&&e.getAcademicClass().getId().equals(courseYearId))&&(status==null||status.isBlank()||displayStatus(a).equalsIgnoreCase(status)||a.getStatus().name().equalsIgnoreCase(status));}
    private boolean paymentMatch(FeePayment p,StudentSectionEnrollment e,String search,Long departmentId,String year,Long courseYearId,String mode,String status){String q=search==null?"":search.trim().toLowerCase(Locale.ROOT);String receipt=receipt(p);return(q.isEmpty()||List.of(p.getStudent().getFullName(),p.getStudent().getAdmissionNumber(),p.getTransactionReference(),Optional.ofNullable(receipt).orElse("")).stream().anyMatch(v->v.toLowerCase(Locale.ROOT).contains(q)))&&(departmentId==null||p.getDepartment().getId().equals(departmentId))&&(year==null||year.isBlank()||p.getStudentFeeAccount().getAcademicYear().equals(year))&&(courseYearId==null||e!=null&&e.getAcademicClass().getId().equals(courseYearId))&&(mode==null||mode.isBlank()||p.getPaymentMode().name().equalsIgnoreCase(mode))&&(status==null||status.isBlank()||p.getStatus().name().equalsIgnoreCase(status));}
    private AccountRow account(StudentFeeAccount a,StudentSectionEnrollment e,List<FeePayment> paymentRows){LocalDate last=paymentRows.stream().filter(p->p.getStudentFeeAccount().getId().equals(a.getId())&&p.getStatus()==PaymentStatus.VERIFIED).map(FeePayment::getPaymentDate).max(LocalDate::compareTo).orElse(null);return new AccountRow(a.getId(),a.getStudent().getId(),a.getStudent().getFullName(),a.getStudent().getAdmissionNumber(),a.getDepartment().getName(),a.getAcademicYear(),e==null?(a.getFeeStructure()==null?"Admission":a.getFeeStructure().getCourseYear()):e.getAcademicClass().getName(),e==null?null:e.getSection().getName(),a.getFeeStructure()==null?"Admission Form Fee":a.getFeeStructure().getTitle(),a.getTotalFee(),a.getPaidAmount(),a.getRemainingAmount(),displayStatus(a),dueDate(a),last);}
    private PaymentRow payment(FeePayment p,StudentSectionEnrollment e,List<FeePayment> all){StudentFeeAccount a=p.getStudentFeeAccount();long previous=all.stream().filter(x->x.getStudentFeeAccount().getId().equals(a.getId())&&x.getStatus()==PaymentStatus.VERIFIED&&x.getSubmittedAt().isBefore(p.getSubmittedAt())).count();String text=(Optional.ofNullable(p.getRemarks()).orElse("")+" "+Optional.ofNullable(p.getRejectionReason()).orElse("")).toLowerCase(Locale.ROOT);String courseYear=e==null?(a.getFeeStructure()==null?"Admission":a.getFeeStructure().getCourseYear()):e.getAcademicClass().getName();String reference=p.getTransactionReference();boolean duplicateReference=reference!=null&&!reference.isBlank()&&all.stream().anyMatch(x->!x.getId().equals(p.getId())&&x.getTransactionReference()!=null&&x.getTransactionReference().equalsIgnoreCase(reference));return new PaymentRow(p.getId(),a.getId(),p.getStudent().getId(),receipt(p),p.getStudent().getFullName(),p.getStudent().getAdmissionNumber(),p.getDepartment().getName(),courseYear,e==null?null:e.getSection().getName(),p.getAmount(),p.getPaymentMode().name(),reference,p.getPaymentDate(),p.getProofUrl(),p.getRemarks(),p.getStatus().name(),p.getSubmittedAt(),p.getVerifiedAt(),p.getVerifiedBy()==null?null:p.getVerifiedBy().getFullName(),p.getRejectedAt(),p.getRejectedBy()==null?null:p.getRejectedBy().getFullName(),p.getRejectionReason(),a.getRemainingAmount(),previous,(int)Math.min(3,previous+1),duplicateReference,text.contains("amount mismatch"));}
    private DueRow due(StudentFeeAccount a,List<FeePayment> rows){LocalDate due=dueDate(a),today=LocalDate.now();String urgency=due.isBefore(today)?"OVERDUE":!due.isAfter(today.plusDays(7))?"DUE_THIS_WEEK":"DUE_THIS_MONTH";LocalDate last=rows.stream().filter(p->p.getStudentFeeAccount().getId().equals(a.getId())&&p.getStatus()==PaymentStatus.VERIFIED).map(FeePayment::getPaymentDate).max(LocalDate::compareTo).orElse(null);return new DueRow(a.getId(),a.getStudent().getId(),a.getStudent().getFullName(),a.getStudent().getAdmissionNumber(),a.getDepartment().getName(),a.getTotalFee(),a.getPaidAmount(),a.getRemainingAmount(),due,last,urgency);}
    private List<InstallmentRow> installments(StudentFeeAccount a){BigDecimal each=a.getTotalFee().divide(BigDecimal.valueOf(3),2,RoundingMode.HALF_UP);List<InstallmentRow> result=new ArrayList<>();BigDecimal covered=a.getPaidAmount();for(int i=1;i<=3;i++){BigDecimal amount=i==3?a.getTotalFee().subtract(each.multiply(BigDecimal.valueOf(2))):each;String status=covered.compareTo(amount)>=0?"PAID":covered.signum()>0?"PARTIALLY_PAID":"PENDING";covered=covered.subtract(amount).max(BigDecimal.ZERO);result.add(new InstallmentRow(i,amount,a.getCreatedAt().toLocalDate().plusDays(i*30L),status));}return result;}
    private List<MoneyPoint> daily(List<FeePayment> rows,LocalDate today){return java.util.stream.IntStream.rangeClosed(0,13).mapToObj(i->today.minusDays(13-i)).map(d->new MoneyPoint(d.getDayOfMonth()+" "+d.getMonth().name().substring(0,3),sum(rows.stream().filter(p->p.getStatus()==PaymentStatus.VERIFIED&&p.getVerifiedAt()!=null&&p.getVerifiedAt().toLocalDate().equals(d)).toList()))).toList();}
    private List<MoneyPoint> monthly(List<FeePayment> rows,LocalDate today){return java.util.stream.IntStream.rangeClosed(0,11).mapToObj(i->YearMonth.from(today).minusMonths(11-i)).map(m->new MoneyPoint(m.getMonth().name().substring(0,3),sum(rows.stream().filter(p->p.getStatus()==PaymentStatus.VERIFIED&&p.getVerifiedAt()!=null&&YearMonth.from(p.getVerifiedAt()).equals(m)).toList()))).toList();}
    private List<MoneyPoint> departments(List<FeePayment> rows){return rows.stream().filter(p->p.getStatus()==PaymentStatus.VERIFIED).collect(Collectors.groupingBy(p->p.getDepartment().getName(),Collectors.reducing(BigDecimal.ZERO,FeePayment::getAmount,BigDecimal::add))).entrySet().stream().map(e->new MoneyPoint(e.getKey(),e.getValue())).sorted(Comparator.comparing(MoneyPoint::value).reversed()).toList();}
    private FeeTransactionResponse transaction(FeeTransaction t){return new FeeTransactionResponse(t.getId(),t.getStudentFeeAccount().getId(),t.getFeePayment()==null?null:t.getFeePayment().getId(),t.getTransactionType(),t.getAmount(),t.getPreviousPaidAmount(),t.getNewPaidAmount(),t.getPreviousRemainingAmount(),t.getNewRemainingAmount(),t.getRemarks(),t.getPerformedBy()==null?null:t.getPerformedBy().getFullName(),t.getCreatedAt());}
    private String displayStatus(StudentFeeAccount a){return a.getRemainingAmount().signum()==0?"FULLY_PAID":a.getPaidAmount().signum()>0?"PARTIALLY_PAID":"PENDING";}private String receipt(FeePayment p){return p.getStatus()==PaymentStatus.VERIFIED?"RCP-"+p.getCollege().getCode()+"-"+p.getPaymentDate().getYear()+"-"+String.format("%06d",p.getId()):null;}private LocalDate dueDate(StudentFeeAccount a){int paidInstallments=a.getTotalFee().signum()==0?3:a.getPaidAmount().multiply(BigDecimal.valueOf(3)).divide(a.getTotalFee(),0,RoundingMode.DOWN).intValue();return a.getCreatedAt().toLocalDate().plusDays(Math.min(3,paidInstallments+1)*30L);}private long count(List<FeePayment> rows,PaymentStatus status){return rows.stream().filter(p->p.getStatus()==status).count();}private BigDecimal sum(List<FeePayment> rows){return rows.stream().map(FeePayment::getAmount).reduce(BigDecimal.ZERO,BigDecimal::add);}private Long college(){Long id=SecurityUtils.requireCurrentUser().getCollegeId();if(id==null)throw new AccessDeniedException("College access is required");return id;}
}
