package com.collegeerp.erp.email.enums;

public enum EmailType {
    USER_ACCOUNT_CREATED,
    PRINCIPAL_ACCOUNT_CREATED,
    ADMISSION_COMPLETED,
    ADMISSION_APPROVED,
    ACCOUNT_ACTIVATED,
    ACCOUNT_DEACTIVATED,
    PASSWORD_RESET,
    PASSWORD_CHANGED,
    VERIFY_EMAIL,
    EMAIL_VERIFIED,
    FEE_PAYMENT_REMINDER
}
