package com.jadhavr.erp.admission.enums;

public enum AdmissionAction {
    STUDENT_DETAILS_SUBMITTED,
    SUBMITTED,
    STUDENT_SECTION_REVIEW_STARTED,
    STUDENT_SECTION_APPROVED,
    STUDENT_SECTION_REJECTED,
    ADMISSION_FORM_PRINTED,
    STATUS_UPDATED,
    FEE_ACCOUNT_CREATED,
    PAYMENT_SUBMITTED,
    PAYMENT_VERIFIED,
    PAYMENT_REJECTED,
    PRINCIPAL_REVIEW_PENDING,
    PRINCIPAL_APPROVED,
    PRINCIPAL_REJECTED
}
